[DO-2133] Added Monetary asset model
3v-workspace/Data_converter pull request #1031
Opened 2021-07-09 08:47 UTC by EmmaSamoilova

2021-07-09 09:01 UTC, roman-tiukh approved these changes

2021-07-09 09:07 UTC, IegorSoboliev requested changes

2021-07-09 09:07 UTC, IegorSoboliev commented on business_register/models/declaration_models.py
> +class MonetaryAsset(DataOceanModel):
MonetaryAssets are our Money?

2021-07-09 09:07 UTC, IegorSoboliev commented on business_register/models/declaration_models.py
> +    quantity = models.FloatField(
Can we also define a currency of cryptocurrency (Bitcoin, etc)

2021-07-09 09:15 UTC, EmmaSamoilova commented on business_register/models/declaration_models.py
> +    quantity = models.FloatField(
this information is specified in 'descriptionObject' (description)

2021-07-09 09:27 UTC, EmmaSamoilova commented on business_register/models/declaration_models.py
> +class MonetaryAsset(DataOceanModel):
I think, the name 'IntangibleAssets' would be better, but Anastasia said in the rules are the name monetary assets. Rename to IntangibleAssets?

2021-07-09 15:00 UTC, IegorSoboliev approved these changes

2021-07-09 15:07 UTC, EmmaSamoilova commented on business_register/converter/declaration.py
> +                and corporate_rights_data.get('person') in self.NO_DATA
I think this is another topic for discussion)

2021-07-10 15:42 UTC, Andrii17s approved these changes

2021-07-10 15:42 UTC, criticus approved these changes

2021-07-10 15:47 UTC, merged