[DO-1858]Added command to save luxury cars and method is_vehicle_luxury
3v-workspace/Data_converter pull request #1045
Opened 2021-07-11 09:28 UTC by EmmaSamoilova

2021-07-11 10:28 UTC, IegorSoboliev requested changes

2021-07-11 10:28 UTC, IegorSoboliev commented on business_register/converter/declaration.py
> +    def is_vehicle_luxury(self, brand, model, year, valuation):
Let's pass to the function the hole Vehicle object with type=Vehicle.Car and validate this

2021-07-11 10:28 UTC, IegorSoboliev commented on business_register/converter/declaration.py
> +        normalized_model = {
I think it`s better first to check is `valuation >= 800000`

2021-07-11 10:28 UTC, IegorSoboliev commented on business_register/converter/declaration.py
> +            brand = data.get('brand') if data.get('brand') not in self.NO_DATA else ''
Are you sure that is a good idea? Bad names are better than no names

2021-07-11 10:28 UTC, IegorSoboliev commented on business_register/converter/declaration.py
> +            year = data.get('graduationYear') if data.get('graduationYear') not in self.NO_DATA else None
same here

2021-07-11 10:28 UTC, IegorSoboliev commented on business_register/converter/declaration.py
> +            year = data.get('graduationYear') if data.get('graduationYear') not in self.NO_DATA else None
and here

2021-07-11 10:28 UTC, IegorSoboliev commented on business_register/converter/declaration.py
> +    def is_vehicle_luxury(self, brand, model, year, valuation):
Then we can use this function not only here

2021-07-11 12:43 UTC, EmmaSamoilova commented on business_register/converter/declaration.py
> +    def is_vehicle_luxury(self, brand, model, year, valuation):
done

2021-07-11 12:43 UTC, EmmaSamoilova commented on business_register/converter/declaration.py
> +        normalized_model = {
done

2021-07-11 12:43 UTC, EmmaSamoilova commented on business_register/converter/declaration.py
> +            brand = data.get('brand') if data.get('brand') not in self.NO_DATA else ''
done

2021-07-11 12:43 UTC, EmmaSamoilova commented on business_register/converter/declaration.py
> +            year = data.get('graduationYear') if data.get('graduationYear') not in self.NO_DATA else None
done

2021-07-11 13:55 UTC, Andrii17s approved these changes

2021-07-11 14:12 UTC, IegorSoboliev approved these changes

2021-07-11 14:12 UTC, IegorSoboliev commented on business_register/pep_scoring/rules.py
> +    message_uk = 'кількість люксових авто - {amount_luxury_cars}'
I would recommend a next text: 
`У декларації зазначено {amount_luxury_cars} авто, ціна яких більше 800 тисяч гривень або які входять да затвердженого урядом...(тут ти краще знаєш)`

2021-07-11 14:15 UTC, IegorSoboliev commented on business_register/pep_scoring/rules.py
> +            weight = 0.4 + (amount_luxury_cars - 1) * 0.1
Is that approved by ANTAC)?

2021-07-12 13:09 UTC, roman-tiukh approved these changes

2021-07-12 13:38 UTC, Andrii17s approved these changes

2021-07-12 13:43 UTC, IegorSoboliev approved these changes

2021-07-12 13:48 UTC, merged