[DO-1724] Finished rule 4 IsResidenceHidden
3v-workspace/Data_converter pull request #1087
Opened 2021-07-13 20:27 UTC by IegorSoboliev

2021-07-13 20:58 UTC, roman-tiukh requested changes

2021-07-13 20:58 UTC, roman-tiukh commented on business_register/pep_scoring/rules.py
> +    rule_id = ScoringRuleEnum.PEP03_car
```suggestion
    rule_id = ScoringRuleEnum.PEP04
```

2021-07-14 07:33 UTC, Andrii17s approved these changes

2021-07-14 08:09 UTC, roman-tiukh approved these changes

2021-07-14 08:09 UTC, merged