[DO-2135]Fix wrong example for API documentation
3v-workspace/Data_converter pull request #1094
Opened 2021-07-14 12:57 UTC by AlenaYanish

2021-07-14 14:26 UTC, Andrii17s approved these changes

2021-07-15 09:39 UTC, Iva-khar approved these changes

2021-07-15 10:14 UTC, roman-tiukh requested changes

2021-07-15 10:14 UTC, roman-tiukh commented on data_ocean/views.py
> +                           f"{'/'.join(operation_keys[:-1])}/"
Wait, is this correct?? Give me example pls

2021-07-16 11:35 UTC, Andrii17s approved these changes

2021-07-21 06:10 UTC, roman-tiukh approved these changes

2021-07-21 06:11 UTC, merged