[DO-1933]Add sanctions against countries and companies to fixture
3v-workspace/Data_converter pull request #1120
Opened 2021-07-20 07:46 UTC by AlenaYanish

2021-07-20 12:47 UTC, Andrii17s approved these changes

2021-07-21 06:05 UTC, roman-tiukh commented on data_ocean/fixtures/register.json
>    }
wrong indents, you have one extra brace - broken json

2021-07-21 06:05 UTC, roman-tiukh requested changes
blocked

2021-07-21 06:06 UTC, roman-tiukh approved these changes

2021-07-21 06:07 UTC, roman-tiukh requested changes
don't merge, we need to have frontend part for this

2021-07-21 11:44 UTC, roman-tiukh approved these changes

2021-07-21 11:44 UTC, merged