[CONTAINS MIGRATION][DO-2198] Save data with unidentified PEP and Company
3v-workspace/Data_converter pull request #1121
Opened 2021-07-20 11:50 UTC by IegorSoboliev

2021-07-20 12:00 UTC, EmmaSamoilova commented on business_register/converter/declaration.py
> -            if not bank_code_en and not bank_code_ua or bank_code_en in all_banks or bank_code_ua in all_banks:
Why did you delete this? It seems to be agreed that banks should not be repeated

2021-07-20 12:16 UTC, EmmaSamoilova commented on business_register/converter/declaration.py
>              income_type = data.get('objectType')
Maybe should delete this line too?

2021-07-20 12:26 UTC, EmmaSamoilova commented on business_register/models/declaration_models.py
> +        (NO_INFO_FROM_FAMILY_MEMBER, 'Family member did not provide the information'),
You added new type NO_INFO_FROM_FAMILY_MEMBER, but didn't added this in save_income to types

2021-07-20 12:49 UTC, IegorSoboliev commented on business_register/models/declaration_models.py
> +        (NO_INFO_FROM_FAMILY_MEMBER, 'Family member did not provide the information'),
Thanks!

2021-07-20 12:49 UTC, IegorSoboliev commented on business_register/converter/declaration.py
> -            if not bank_code_en and not bank_code_ua or bank_code_en in all_banks or bank_code_ua in all_banks:
I see. Restored

2021-07-20 12:57 UTC, IegorSoboliev commented on business_register/converter/declaration.py
>              income_type = data.get('objectType')
Thanks! Deleted with TODO)

2021-07-20 13:02 UTC, EmmaSamoilova approved these changes

2021-07-21 05:59 UTC, roman-tiukh requested changes

2021-07-21 05:59 UTC, roman-tiukh commented on business_register/converter/declaration.py
> +        )
`'UNIDENTIFIED_PEP'` - should be constant
```suggestion
        self.UNIDENTIFIED_PEP = Pep.get_unidentified_pep()
```

2021-07-21 05:59 UTC, roman-tiukh commented on business_register/converter/declaration.py
> +        )
`'UNIDENTIFIED_COMPANY'` - should be constant
```suggestion
        self.UNIDENTIFIED_COMPANY = Company.get_unidentified_company()
```

2021-07-21 05:59 UTC, roman-tiukh commented on business_register/converter/declaration.py
> +                if owner_id == self.DECLARANT:
:+1:

2021-07-21 05:59 UTC, roman-tiukh commented on business_register/models/declaration_models.py
> +        'registration number',
Minor:
redundant verbose_name, it duplicate info in field name

2021-07-21 07:15 UTC, IegorSoboliev commented on business_register/converter/declaration.py
> +        )
done

2021-07-21 07:15 UTC, IegorSoboliev commented on business_register/converter/declaration.py
> +        )
done

2021-07-21 08:26 UTC, roman-tiukh approved these changes

2021-07-21 08:41 UTC, merged