[DO-2201] added data correction method dor declaration in wrong format
3v-workspace/Data_converter pull request #1122
Opened 2021-07-20 13:39 UTC by EmmaSamoilova

2021-07-20 17:23 UTC, Andrii17s approved these changes

2021-07-21 05:46 UTC, roman-tiukh requested changes

2021-07-21 05:46 UTC, roman-tiukh commented on business_register/converter/declaration.py
> +            for data in step_items:
```suggestion
            step_data = self.get_step_data(step, declaration_data)
            if step in ('step_0', 'step_1') or not step_data:
                continue
            for key, data in step_data.items():
```

2021-07-21 05:46 UTC, roman-tiukh commented on business_register/converter/declaration.py
> +                    data[1]['rights'] = [right[1] for right in rights]
```suggestion
                    data[1]['rights'] = rights.values()
```

2021-07-21 05:46 UTC, roman-tiukh commented on business_register/converter/declaration.py
> +            declaration_data[step]['data'] = [item[1] for item in step_items]
```suggestion
            declaration_data[step]['data'] = step_data.values()
```

2021-07-21 05:46 UTC, roman-tiukh commented on business_register/converter/declaration.py
> +                        if not right[1].get('rightBelongs') and right[0] in ('j', '1'):
replace `'j', '1'` with constants

2021-07-21 05:46 UTC, roman-tiukh commented on business_register/converter/declaration.py
> +                if data[1].get('rights'):
```suggestion
                if 'rights' in data:
```

2021-07-21 05:46 UTC, roman-tiukh commented on business_register/converter/declaration.py
> +                    data[1].update({'id': data[0]})
```suggestion
                    data['id'] = key
```

2021-07-21 05:46 UTC, roman-tiukh commented on business_register/converter/declaration.py
> +                    for right in rights:
```suggestion
                    for key, right_data in data['rights'].items():
```

2021-07-21 08:35 UTC, EmmaSamoilova commented on business_register/converter/declaration.py
> +            for data in step_items:
done

2021-07-21 08:36 UTC, EmmaSamoilova commented on business_register/converter/declaration.py
> +                    data[1]['rights'] = [right[1] for right in rights]
done

2021-07-21 08:36 UTC, EmmaSamoilova commented on business_register/converter/declaration.py
> +            declaration_data[step]['data'] = [item[1] for item in step_items]
done

2021-07-21 08:36 UTC, EmmaSamoilova commented on business_register/converter/declaration.py
> +                if data[1].get('rights'):
done

2021-07-21 08:37 UTC, EmmaSamoilova commented on business_register/converter/declaration.py
> +                    data[1].update({'id': data[0]})
done

2021-07-21 08:37 UTC, EmmaSamoilova commented on business_register/converter/declaration.py
> +                    for right in rights:
done

2021-07-21 08:44 UTC, IegorSoboliev approved these changes

2021-07-21 10:59 UTC, roman-tiukh approved these changes

2021-07-21 11:48 UTC, merged