[DO-2077] Add search filter to export xlsx
3v-workspace/Data_converter pull request #1141
Opened 2021-07-28 11:11 UTC by Iva-khar

2021-07-29 06:34 UTC, roman-tiukh requested changes

2021-07-29 06:34 UTC, roman-tiukh commented on data_ocean/export.py
> +        request = requests
use native request object from django DRF

2021-07-29 06:34 UTC, roman-tiukh commented on data_ocean/export.py
>          serializer = import_string(serializer_module)(queryset, many=True)
you can omit serializer, it redundant

2021-07-29 13:19 UTC, Iva-khar commented on data_ocean/export.py
> +        request = requests
done

2021-07-29 13:23 UTC, Iva-khar commented on data_ocean/export.py
>          serializer = import_string(serializer_module)(queryset, many=True)
I need serializer for `pep_type_display` field, that generates in serializer

2021-07-30 06:38 UTC, roman-tiukh approved these changes

2021-07-30 08:44 UTC, merged