[DO-2033] Pdf pep
3v-workspace/Data_converter pull request #1143
Opened 2021-07-28 14:02 UTC by Iva-khar

2021-07-29 06:52 UTC, roman-tiukh requested changes

2021-07-29 06:52 UTC, roman-tiukh commented on business_register/views/pep_views.py
> +        return PDFViewMixin(serializer.data)
redundant code

2021-07-29 06:52 UTC, roman-tiukh commented on business_register/views/pep_views.py
> +        return 'pep_' + str(context['id'])
```suggestion
        return f'pep_{self.object.id}.pdf'
```

2021-07-29 06:52 UTC, roman-tiukh commented on business_register/views/pep_views.py
> +        return self.template_name
delete this

2021-07-29 06:52 UTC, roman-tiukh commented on business_register/views/pep_views.py
> +    serializer_class = PepDetailSerializer
delete this

2021-07-29 06:52 UTC, roman-tiukh commented on business_register/views/pep_views.py
> +    template_name = 'pdf/pep.html'
```suggestion
    template_name = 'business_register/pep/pep_pdf.html'
```

2021-07-29 06:52 UTC, roman-tiukh commented on business_register/views/pep_views.py
> +from data_ocean.views import CachedViewSetMixin, RegisterViewMixin, PDFViewMixin, PDFDetailView
```suggestion
from data_ocean.views import CachedViewSetMixin, RegisterViewMixin, PDFDetailView
```

2021-07-29 06:52 UTC, roman-tiukh commented on data_converter/urls.py
> +    path('pdf/pep/<int:pk>/', PepPDFView.as_view())
```suggestion
    path('api/pep/<int:pk>/pdf/', PepPDFView.as_view())
```

2021-07-29 06:52 UTC, roman-tiukh commented on data_ocean/views.py
> +        return model_to_dict(self.object)
Nooo, you don't need this

2021-07-29 06:52 UTC, roman-tiukh commented on data_ocean/views.py
> +        #     extra['font_config'] = FontConfiguration()
why you comment this???

2021-07-29 06:52 UTC, roman-tiukh commented on business_register/views/pep_views.py
> +    queryset = Pep.objects.all()
Add permission_classes

2021-07-29 10:50 UTC, Iva-khar commented on business_register/views/pep_views.py
> +        return PDFViewMixin(serializer.data)
deleted

2021-07-29 10:52 UTC, Iva-khar commented on business_register/views/pep_views.py
> +        return 'pep_' + str(context['id'])
done

2021-07-29 10:53 UTC, Iva-khar commented on business_register/views/pep_views.py
> +        return self.template_name
`AttributeError: 'PepPDFView' object has no attribute 'get_template_names'`

2021-07-29 10:58 UTC, Iva-khar commented on business_register/views/pep_views.py
> +from data_ocean.views import CachedViewSetMixin, RegisterViewMixin, PDFViewMixin, PDFDetailView
done

2021-07-29 14:21 UTC, Iva-khar commented on business_register/views/pep_views.py
> +    serializer_class = PepDetailSerializer
done

2021-07-29 14:25 UTC, Iva-khar commented on business_register/views/pep_views.py
> +    template_name = 'pdf/pep.html'
done

2021-07-29 14:28 UTC, Iva-khar commented on data_converter/urls.py
> +    path('pdf/pep/<int:pk>/', PepPDFView.as_view())
done

2021-07-29 14:41 UTC, Iva-khar commented on data_ocean/views.py
> +        #     extra['font_config'] = FontConfiguration()
uncommented

2021-07-29 14:43 UTC, Iva-khar commented on business_register/views/pep_views.py
> +    queryset = Pep.objects.all()
done

2021-07-29 15:21 UTC, Iva-khar commented on data_ocean/views.py
> +        return model_to_dict(self.object)
rewrited

2021-07-30 06:43 UTC, roman-tiukh requested changes
no PermissionViewMixin.
Still in work

2021-07-30 06:43 UTC, roman-tiukh commented on data_ocean/views.py
> +        return FileResponse(file, content_type='application/pdf')
no get_context_data with user.

2021-07-30 06:43 UTC, roman-tiukh commented on data_ocean/views.py
> +        return super().get(request, *args, **kwargs)
no get_context_data with object

2021-08-02 13:38 UTC, closed without merging