[Contains migrations] added last_employer_en and last_job_title_en fi…
3v-workspace/Data_converter pull request #1147
Opened 2021-07-29 15:15 UTC by EmmaSamoilova

…elds to Pep model

2021-07-30 06:34 UTC, roman-tiukh requested changes

2021-07-30 06:34 UTC, roman-tiukh commented on business_register/management/commands/add_transaltion_to_last_job.py
> +            pep.save()
```suggestion
        for pep in Pep.objects.filter(last_employer__isnull=False):
            pep.last_employer_en = transliterate(
                translate_company_type_in_string(pep.last_employer)
            )
            pep.save(update_fields=['last_employer_en'])
        for pep in Pep.objects.filter(last_job_title__isnull=False):
            pep.last_job_title_en = transliterate(
                 translate_last_position_in_string(pep.last_job_title)
            )
            pep.save(update_fields=['last_job_title_en'])
```

2021-07-30 06:34 UTC, roman-tiukh commented on business_register/filters.py
> +            ('last_job_title_en', 'last_job_title_en'),
How about fullame_en ordering?

2021-07-30 09:26 UTC, EmmaSamoilova commented on business_register/management/commands/add_transaltion_to_last_job.py
> +            pep.save()
done

2021-07-30 09:26 UTC, EmmaSamoilova commented on business_register/filters.py
> +            ('last_job_title_en', 'last_job_title_en'),
done

2021-07-30 10:37 UTC, Andrii17s requested changes

2021-07-30 10:37 UTC, Andrii17s commented on business_register/models/pep_models.py
> +        help_text='Title of the last job in Ukrainian.'
Is it in Ukrainian?

2021-07-30 10:37 UTC, Andrii17s commented on business_register/models/pep_models.py
> +        help_text='Last employer in Ukrainian.'
Is it in Ukrainian?

2021-07-30 13:53 UTC, EmmaSamoilova commented on business_register/models/pep_models.py
> +        help_text='Last employer in Ukrainian.'
No, thank you. I have done

2021-07-30 14:10 UTC, Andrii17s approved these changes

2021-08-02 16:33 UTC, Iva-khar commented on business_register/filters.py
> +            ('last_job_title_en', 'last_job_title_en'),
2 times `last_job_title_en`, but no one` last_employer_en`

2021-08-02 16:33 UTC, Iva-khar commented on business_register/management/commands/add_transaltion_to_last_job.py
> +    help = 'Saving a list of cars that are subject to transport tax'
change help text or remove

2021-08-03 06:53 UTC, roman-tiukh approved these changes

2021-08-03 09:22 UTC, IegorSoboliev approved these changes

2021-08-03 09:26 UTC, merged