[DO-1861]  [Contains migration] Improve pep model
3v-workspace/Data_converter pull request #1148
Opened 2021-08-02 10:50 UTC by Iva-khar

- field `pep.sanctions` without 'null' value, with '' instead
- migration for convertind 'null' to ''
- pep converter with '' if sanctions is absent

2021-08-02 12:56 UTC, EmmaSamoilova commented on business_register/converter/pep.py
> +            sanctions = pep_dict.get('reputation_sanctions_uk') or ''
maybe sanctions = pep_dict.get('reputation_sanctions_uk', '') ?

2021-08-02 15:40 UTC, Iva-khar commented on business_register/converter/pep.py
> +            sanctions = pep_dict.get('reputation_sanctions_uk') or ''
yes. done.

2021-08-02 16:18 UTC, EmmaSamoilova approved these changes

2021-08-03 06:40 UTC, roman-tiukh commented
same comment as in #1155

2021-08-03 06:40 UTC, roman-tiukh requested changes
same comment as in #1155

2021-08-03 15:38 UTC, Iva-khar commented
Add method for change null value to '' in migration

2021-08-04 06:56 UTC, roman-tiukh requested changes

2021-08-04 06:56 UTC, roman-tiukh commented on business_register/migrations/0155_auto_20210802_1022.py
> +                historical_instance.save(update_fields=['sanctions'])
move this function from Migration class to module

2021-08-04 06:56 UTC, roman-tiukh commented on business_register/migrations/0155_auto_20210802_1022.py
> +                historical_instance.save(update_fields=['sanctions'])
https://github.com/3v-workspace/Data_converter/pull/1155/files#r682336319

2021-08-05 09:33 UTC, Iva-khar commented on business_register/migrations/0155_auto_20210802_1022.py
> +                historical_instance.save(update_fields=['sanctions'])
done

2021-08-06 08:18 UTC, roman-tiukh approved these changes

2021-08-06 08:22 UTC, merged