default ordering company sanctions
3v-workspace/Data_converter pull request #1154
Opened 2021-08-02 17:32 UTC by Iva-khar

2021-08-02 21:22 UTC, Andrii17s approved these changes

2021-08-03 06:18 UTC, roman-tiukh requested changes
Wrong way. Just add `order_by` to queryset.

2021-08-03 15:48 UTC, Iva-khar commented
> Wrong way. Just add `order_by` to queryset.

done

2021-08-04 06:57 UTC, roman-tiukh approved these changes

2021-08-05 07:15 UTC, EmmaSamoilova approved these changes

2021-08-05 08:42 UTC, merged