[DO-2324] Empty string instead null
3v-workspace/Data_converter pull request #1155
Opened 2021-08-02 18:00 UTC by Iva-khar

Expected result:
In every "criminal_proceedings" field without data value is empty quotes

2021-08-02 21:31 UTC, Andrii17s approved these changes

2021-08-03 06:17 UTC, roman-tiukh requested changes
Migrations will ends with error. You need to add **migration step** for change existing values in DB from NULL to `''`.

2021-08-03 10:04 UTC, Iva-khar commented
> Migrations will ends with error. You need to add **migration step** for change existing values in DB from NULL to `''`.

It works locally without any errors.

2021-08-03 14:00 UTC, Iva-khar commented
Add method for change null values to '' in migration

2021-08-04 06:52 UTC, roman-tiukh approved these changes

2021-08-04 06:52 UTC, roman-tiukh commented on business_register/migrations/0155_auto_20210802_1752.py
> +            historical_instance.save(update_fields=['criminal_proceedings'])
```suggestion
def change_null_to_blank(apps, schema_editor):
    Pep = apps.get_model('business_register', 'Pep')
    for pep in Pep.objects.all():
        if not pep.criminal_proceedings:
            pep.criminal_proceedings = ''
            pep.save(update_fields=['criminal_proceedings'])
    HistoricalPep = apps.get_model('business_register', 'HistoricalPep')
    for pep in HistoricalPep.objects.all():
        if not pep.criminal_proceedings:
            pep.criminal_proceedings = ''
            pep.save(update_fields=['criminal_proceedings'])
```

2021-08-05 09:08 UTC, Iva-khar commented on business_register/migrations/0155_auto_20210802_1752.py
> +            historical_instance.save(update_fields=['criminal_proceedings'])
done

2021-08-05 09:08 UTC, merged