[DO-1689][Contains migration] fixed sorting of last_employer and last_job_title fields
3v-workspace/Data_converter pull request #1156
Opened 2021-08-03 13:51 UTC by EmmaSamoilova

improve Pep model: changed null=True to default=''
changed ordering: symbols should be first, empty string or '-' last

2021-08-03 14:04 UTC, criticus commented
is this migration affecting existing records? Would their `updated_at` field be updated?

2021-08-03 14:13 UTC, Andrii17s approved these changes

2021-08-03 14:32 UTC, EmmaSamoilova commented
> is this migration affecting existing records? Would their `updated_at` field be updated?
I applied this migration locally today. updated_at field was not changed and my records were not lost

2021-08-04 07:05 UTC, roman-tiukh requested changes
Look at this PR #1155

2021-08-05 05:29 UTC, roman-tiukh requested changes

2021-08-05 05:29 UTC, roman-tiukh commented on business_register/converter/pep.py
>              if last_employer:
PepJsonConverter not used now

2021-08-06 08:15 UTC, roman-tiukh requested changes

2021-08-06 08:15 UTC, roman-tiukh commented on data_ocean/filters.py
> +        NULL_LAST_PARAM = ('last_employer', 'last_job_title', 'last_employer_en', 'last_job_title_en')
This configuration must be passed into `__init__` methods

2021-08-06 08:15 UTC, roman-tiukh commented on data_ocean/filters.py
> +            qs = qs.annotate(param=NullIf(f'{value[0]}', Value(''))).order_by('param')
param... param must be generated from value

2021-08-06 10:32 UTC, EmmaSamoilova commented on data_ocean/filters.py
> +            qs = qs.annotate(param=NullIf(f'{value[0]}', Value(''))).order_by('param')
done

2021-08-06 10:32 UTC, EmmaSamoilova commented on data_ocean/filters.py
> +        NULL_LAST_PARAM = ('last_employer', 'last_job_title', 'last_employer_en', 'last_job_title_en')
done

2021-08-09 05:13 UTC, roman-tiukh approved these changes

2021-08-09 05:13 UTC, roman-tiukh commented on data_ocean/filters.py
> +        self.NULL_LAST_PARAM = kwargs.pop('null_last_param', ())
```suggestion
        self.null_last_fields = kwargs.pop('null_last_fields', ())
```

2021-08-09 07:32 UTC, EmmaSamoilova commented on data_ocean/filters.py
> +        self.NULL_LAST_PARAM = kwargs.pop('null_last_param', ())
done

2021-08-09 08:00 UTC, Andrii17s approved these changes

2021-08-09 08:03 UTC, merged