[DO-1657]Create multiselect filter for PEP type column
3v-workspace/Data_converter pull request #1169
Opened 2021-08-10 10:14 UTC by AlenaYanish

2021-08-10 10:27 UTC, Iva-khar approved these changes

2021-08-11 06:08 UTC, roman-tiukh commented on business_register/filters.py
> +                  '(pep_type=member of PEP`s family). You can select more than one type.',
> You can select more than one type

But how?

2021-08-12 07:25 UTC, roman-tiukh requested changes

2021-08-12 07:25 UTC, roman-tiukh commented on business_register/filters.py
>      )
try `in` lookup for comma separated parameters `id=1,2,3,4`

2021-08-12 07:49 UTC, roman-tiukh approved these changes

2021-08-12 07:49 UTC, merged