[DO-2386][Contains migration] Provide full localization for KVED register
3v-workspace/Data_converter pull request #1178
Opened 2021-08-12 20:25 UTC by Andrii17s

https://razom.atlassian.net/browse/DO-2386
According to the attachment document save translation for each column in the register

2021-08-18 17:17 UTC, EmmaSamoilova approved these changes

2021-08-19 15:28 UTC, AlenaYanish approved these changes

2021-08-23 06:32 UTC, roman-tiukh requested changes
Update migration pls. For now, we have 0162 as the maximum migration number

2021-08-23 06:32 UTC, roman-tiukh commented on business_register/management/commands/fill_eng_kveds.py
> +            print(arg, KvedSection.objects.all())
print?

2021-08-23 06:32 UTC, roman-tiukh commented on business_register/management/commands/fill_eng_kveds.py
> +            args = ['KVED_SECTIONS', 'KVED_GROUPS', 'KVED_DIVISIONS', 'KVEDS']
How you can set these args?
Why not make command arguments?

2021-08-23 06:32 UTC, roman-tiukh commented on business_register/management/commands/fill_eng_kveds.py
> +            for row in range(1, sheet_obj.max_row):
you can use `iter_rows` for this

2021-08-23 06:32 UTC, roman-tiukh commented on business_register/management/commands/fill_eng_kveds.py
> +            if arg == 'KVED_GROUPS':
elif

2021-08-23 06:32 UTC, roman-tiukh commented on business_register/management/commands/fill_eng_kveds.py
> +            if arg == 'KVED_DIVISIONS':
elif

2021-08-23 06:32 UTC, roman-tiukh commented on business_register/management/commands/fill_eng_kveds.py
> +            if arg == 'KVEDS':
elif

2021-08-23 06:32 UTC, roman-tiukh commented on business_register/management/commands/fill_eng_kveds.py
> +        wb = load_workbook('kveds.xlsx')
Don't put your files at the root of the project...
Look at other similar cases.

2021-08-23 11:56 UTC, closed without merging