[DO-2397]PepAdditionalInfo API
3v-workspace/Data_converter pull request #1195
Opened 2021-08-20 15:06 UTC by IegorSoboliev

2021-08-31 09:45 UTC, EmmaSamoilova approved these changes

2021-08-31 10:51 UTC, roman-tiukh requested changes
1. Need internal access only.
2. Disable documentation generation

2021-08-31 10:51 UTC, roman-tiukh commented on business_register/serializers/declaration_serializers.py
> +    paid_by_company = serializers.SerializerMethodField()
I think this can be a nested company serializer

2021-08-31 10:51 UTC, roman-tiukh commented on business_register/serializers/declaration_serializers.py
> +    is_gift = serializers.SerializerMethodField()
make a property in model Income

2021-08-31 10:51 UTC, roman-tiukh commented on business_register/serializers/declaration_serializers.py
> +    liability_type = serializers.CharField(source='get_type_display', max_length=60)
no need max_length

2021-08-31 10:51 UTC, roman-tiukh commented on business_register/serializers/declaration_serializers.py
> +    owner_id = serializers.IntegerField(source='owner.id')
maybe nested serializer for owner?

2021-08-31 10:51 UTC, roman-tiukh commented on business_register/serializers/declaration_serializers.py
> +    recipient_employer = serializers.CharField(source='declaration.last_employer', max_length=500)
nested serializer for recipient?

2021-08-31 10:51 UTC, roman-tiukh commented on business_register/serializers/declaration_serializers.py
> +    declared_resignation_at = serializers.SerializerMethodField()
make a property in model

2021-08-31 10:51 UTC, roman-tiukh commented on business_register/serializers/sanction_serializers.py
> +        )
I think this should be API with aggregated types_of_sanctions,  as this is required by the frontend. 
We will not perform data aggregation on the frontend side.

2021-08-31 14:27 UTC, IegorSoboliev commented on business_register/serializers/declaration_serializers.py
> +    recipient_full_name = serializers.CharField(source='recipient.fullname', max_length=75)
deleted

2021-08-31 14:31 UTC, IegorSoboliev commented on business_register/serializers/declaration_serializers.py
> +    paid_by_company = serializers.SerializerMethodField()
changed to CompanyShortSerializer

2021-08-31 14:35 UTC, IegorSoboliev commented on business_register/serializers/declaration_serializers.py
> +    liability_type = serializers.CharField(source='get_type_display', max_length=60)
deleted

2021-08-31 16:58 UTC, IegorSoboliev commented on business_register/serializers/declaration_serializers.py
> +    declared_resignation_at = serializers.SerializerMethodField()
done

2021-08-31 16:58 UTC, IegorSoboliev commented on business_register/serializers/declaration_serializers.py
> +    recipient_employer = serializers.CharField(source='declaration.last_employer', max_length=500)
done

2021-08-31 16:58 UTC, IegorSoboliev commented on business_register/serializers/declaration_serializers.py
> +    owner_id = serializers.IntegerField(source='owner.id')
good idea, use PepShortSerializer

2021-08-31 16:59 UTC, IegorSoboliev commented on data_ocean/utils.py
> +def get_attribute_if_exists(obj, attribute_name):
deleted

2021-08-31 17:02 UTC, IegorSoboliev commented
> 1. Need internal access only.
> 2. Disable documentation generation

Used schema = None. Let`s discuss and define access in another PR

2021-09-01 06:33 UTC, roman-tiukh approved these changes

2021-09-01 06:33 UTC, roman-tiukh commented on business_register/models/declaration_models.py
> +        return
Explicit is better than implicit
```suggestion
        return None
```

2021-09-01 08:09 UTC, EmmaSamoilova approved these changes

2021-09-02 07:38 UTC, merged