[DO-1895] Capitalize country names in DB
3v-workspace/Data_converter pull request #1200
Opened 2021-08-31 13:04 UTC by Iva-khar

A Part of Task DO-1895 - Rewrite existing fields stored in lowercase

2021-09-01 09:43 UTC, roman-tiukh requested changes

2021-09-01 09:43 UTC, roman-tiukh commented on data_ocean/converter.py
>          if name not in self.all_countries_dict:
this comparing should be case insesitive

2021-09-01 13:21 UTC, Iva-khar commented on location_register/management/commands/capitalize_country_names.py
> +            country = Country.objects.filter(name=name).first()
done

2021-09-01 13:46 UTC, Iva-khar commented on location_register/management/commands/constants.py
> +	'belize': 'Belize',
done

2021-09-01 14:16 UTC, Iva-khar commented on data_ocean/converter.py
>          if name not in self.all_countries_dict:
done

2021-09-02 10:01 UTC, Andrii17s approved these changes

2021-09-03 06:28 UTC, roman-tiukh requested changes
Check this:
- DeclarationConverter.find_country
- load_companies_sanctions.py
- AddressConverter.save_or_get_country
- load_person_sanctions.py
- add_country_ukrainian_name.py
- and maybe in some other places

2021-09-03 06:28 UTC, roman-tiukh commented on location_register/converter/address.py
>      def save_or_get_country(self, name):
in this function?
is this duplicate of Converter.save_or_get_country?

2021-09-03 09:00 UTC, Iva-khar commented on location_register/converter/address.py
>      def save_or_get_country(self, name):
yes, it's just duplicate.
`address.py` - deleted;
usages - `ukr_company.py, ukr_company_full.py, pep.py` - modificated

2021-09-03 09:28 UTC, Iva-khar commented
> Check this:
> 
> * DeclarationConverter.find_country
> * load_companies_sanctions.py
> * AddressConverter.save_or_get_country
> * load_person_sanctions.py
> * add_country_ukrainian_name.py
> * and maybe in some other places
Checked. Besides checked all usages of `Country` model. Additionaly modificated `load_companies_sanctions.py` & `load_person_sanctions.py`

2021-09-03 09:39 UTC, roman-tiukh approved these changes

2021-09-03 09:46 UTC, merged