Serializers for kved and pep.is_pep
3v-workspace/Data_converter pull request #1202
Opened 2021-08-31 20:24 UTC by Andrii17s

2021-09-01 06:12 UTC, roman-tiukh requested changes

2021-09-01 06:12 UTC, roman-tiukh commented on business_register/serializers/kved_serializers.py
> +                  'section_en', 'division_en', 'group_en']
incorrect sequence of field

2021-09-01 06:12 UTC, roman-tiukh commented on business_register/serializers/sanction_serializers.py
> +        source='pep.is_pep', default=False,
maybe better `default=None`

2021-09-01 10:05 UTC, roman-tiukh requested changes

2021-09-01 10:05 UTC, roman-tiukh commented on business_register/serializers/sanction_serializers.py
> +        help_text='Чи є особа під санкціями публичним діячем України'
1. translate to English, need for API documentation
2. remove "України" from help_text

2021-09-02 06:14 UTC, roman-tiukh approved these changes

2021-09-02 06:14 UTC, roman-tiukh commented on business_register/serializers/sanction_serializers.py
> +from django.utils.translation import ugettext_lazy as _
```suggestion
from django.utils.translation import gettext_lazy as _
```

2021-09-03 06:40 UTC, roman-tiukh approved these changes

2021-09-03 09:58 UTC, AlenaYanish approved these changes

2021-09-03 10:12 UTC, merged