[DO-2471]Made Person model
3v-workspace/Data_converter pull request #1205
Opened 2021-09-06 16:03 UTC by IegorSoboliev

2021-09-06 16:05 UTC, IegorSoboliev commented
Please, look and after all improvements, I will add the migration)

2021-09-07 07:01 UTC, roman-tiukh requested changes

2021-09-07 07:35 UTC, EmmaSamoilova approved these changes

2021-09-07 09:02 UTC, IegorSoboliev commented on person/models.py
> +        validators=[RegexValidator(regex=r'[A-Za-z]')],
added

2021-09-07 09:19 UTC, IegorSoboliev commented on person/models.py
> +        validators=[RegexValidator(regex=r'[A-Za-z]')],
and made custom validator

2021-09-07 09:19 UTC, IegorSoboliev commented on person/models.py
> +        _('first name'),
deleted)

2021-09-07 09:26 UTC, IegorSoboliev commented on person/models.py
> +    full_name_options = ArrayField(
changed

2021-09-07 09:28 UTC, IegorSoboliev commented on person/models.py
> +        _('date of birth  of the person'),
thank you, fixed

2021-09-07 09:33 UTC, IegorSoboliev commented on person/models.py
> +    )
added as default

2021-09-07 09:33 UTC, IegorSoboliev commented on person/models.py
> +    )
added as default

2021-09-07 09:38 UTC, IegorSoboliev commented on person/models.py
> +        on_delete=models.CASCADE,
changed

2021-09-07 10:13 UTC, IegorSoboliev commented on person/models.py
> +        default=True,
changed

2021-09-07 10:13 UTC, IegorSoboliev commented on person/models.py
> +        return f'{self.full_name} from {self.residence}'
changed

2021-09-07 10:17 UTC, IegorSoboliev commented on person/models.py
> +        help_text=_('duplicate of the record of the person'),
added

2021-09-07 10:19 UTC, IegorSoboliev commented on person/models.py
> +        unique_together = ('full_name', 'date_of_birth', 'taxpayer_number')
added verbose_name_plural

2021-09-07 10:19 UTC, IegorSoboliev commented on person/models.py
> +        choices=CitizenshipStatus.choices,
added

2021-09-07 10:19 UTC, IegorSoboliev commented on person/models.py
> +        validators=[RegexValidator(regex=r'[A-Za-z]')],
changed

2021-09-07 10:24 UTC, IegorSoboliev commented on person/models.py
> +            raise ValidationError('Record of Person cannot be main and duplicate of')
changed

2021-09-07 10:52 UTC, IegorSoboliev commented on person/models.py
> +            raise ValidationError('Record of Person cannot be main and duplicate of')
thank you, fixed

2021-09-07 11:09 UTC, IegorSoboliev commented on person/models.py
> +        self.full_name_original = f'{self.last_name_original} {self.first_name_original} {self.middle_name_original}'
thank you, fixed

2021-09-07 14:00 UTC, roman-tiukh approved these changes

2021-09-07 14:00 UTC, roman-tiukh commented on person/models.py
> +            raise ValidationError({'duplicate of': 'Record cannot be main and duplicate'})
```suggestion
            raise ValidationError({'duplicate_of': 'Record cannot be main and duplicate'})
```

2021-09-07 15:05 UTC, roman-tiukh commented on data_ocean/models.py
> +            if field is str:
```suggestion
            if isinstance(field, CharField):
```

2021-09-07 15:05 UTC, roman-tiukh commented on person/models.py
> +        DOBAccuracyChoices.date_of_birth_str(self.date_of_birth, self.date_of_birth_accuracy)
```suggestion
        return DOBAccuracyChoices.date_of_birth_str(self.date_of_birth, self.date_of_birth_accuracy)
```

2021-09-07 18:44 UTC, EmmaSamoilova approved these changes

2021-09-07 19:20 UTC, IegorSoboliev commented on person/models.py
> +        DOBAccuracyChoices.date_of_birth_str(self.date_of_birth, self.date_of_birth_accuracy)
thank you)

2021-09-07 21:05 UTC, IegorSoboliev commented on data_ocean/models.py
> +            if field is str:
that was only direction, not implementation))

2021-09-07 21:07 UTC, merged

2021-09-08 06:07 UTC, roman-tiukh commented on business_register/locale/uk/LC_MESSAGES/django.po
> +msgid "associated person"
persons