Add admin action for Sanction actualize (DO-2240)
3v-workspace/Data_converter pull request #1217
Opened 2021-09-10 11:44 UTC by PyDev777

2021-09-10 12:19 UTC, IegorSoboliev commented
@PyDev777 let`s discuss logic in a separate meeting with @roman-tiukh ?

2021-09-13 06:01 UTC, roman-tiukh commented on business_register/admin.py
> +def actualize_noqs(o):
what is this?

2021-09-13 14:12 UTC, PyDev777 commented on business_register/admin.py
> +def actualize_action(o, req):
"o" is "self" object

2021-09-13 14:13 UTC, PyDev777 commented on business_register/admin.py
> +def actualize_noqs(o):
Action can run without items check

2021-09-14 07:38 UTC, roman-tiukh requested changes

2021-09-14 07:38 UTC, roman-tiukh commented on business_register/admin.py
> +def actualize_action(o, req):
```suggestion
def actualize_action(model_admin, request):
```

2021-09-14 07:38 UTC, roman-tiukh commented on business_register/admin.py
> +        self.req = request
```suggestion
```

2021-09-14 07:38 UTC, roman-tiukh commented on business_register/admin.py
> +def actualize_noqs(o):
```suggestion
def actualize_noqs(model_admin):
```

2021-09-14 07:38 UTC, roman-tiukh commented on business_register/admin.py
> +        post = o.req.POST.copy()
```suggestion
        post = model_admin.request.POST.copy()
```

2021-09-16 13:17 UTC, PyDev777 commented on business_register/admin.py
> +        post = o.req.POST.copy()
Fixed in new commit

2021-09-16 13:18 UTC, PyDev777 commented on business_register/admin.py
> +def actualize_noqs(o):
Fixed in new commit

2021-09-16 13:18 UTC, PyDev777 commented on business_register/admin.py
> +        self.req = request
Fixed in new commit

2021-09-16 13:18 UTC, PyDev777 commented on business_register/admin.py
> +def actualize_action(o, req):
Fixed in new commit

2021-09-16 13:18 UTC, PyDev777 commented on business_register/admin.py
> +def actualize_action(o, req):
req -> request
Fixed in new commit

2021-09-17 06:14 UTC, roman-tiukh approved these changes

2021-09-17 06:31 UTC, merged