Added method get_other_companies_founded_by_person_with_the_same_full…
3v-workspace/Data_converter pull request #271
Opened 2020-08-18 17:54 UTC by IegorSoboliev

…name to PepSerializer

2020-08-18 18:41 UTC, roman-tiukh requested changes

2020-08-18 18:41 UTC, roman-tiukh commented on business_register/serializers/pep_serializers.py
> +    other_companies_founded_by_person_with_the_same_fullname = serializers.SerializerMethodField()
this is the longest property name i have ever seen =))), maybe shorten it?

2020-08-18 18:41 UTC, roman-tiukh commented on business_register/serializers/pep_serializers.py
> +            if founder.company not in pep.related_companies:
```suggestion
        founder_of = Founder.objects.filter(
            name__contains=pep.fullname
        ).exclude(company__in=pep.related_companies)
        other_companies_founded_by_person_with_the_same_fullname = []
        for founder in founder_of:
```

2020-08-19 10:18 UTC, IegorSoboliev commented on business_register/serializers/pep_serializers.py
> +    other_companies_founded_by_person_with_the_same_fullname = serializers.SerializerMethodField()
My first language was Java). Done

2020-08-19 10:19 UTC, IegorSoboliev commented on business_register/serializers/pep_serializers.py
> +            if founder.company not in pep.related_companies:
Thought about this

2020-08-19 10:23 UTC, IegorSoboliev commented on business_register/serializers/pep_serializers.py
> +            if founder.company not in pep.related_companies:
But used another logic in the end. Please, review the new one

2020-08-19 14:13 UTC, roman-tiukh approved these changes

2020-08-19 14:14 UTC, merged