Made different serializers for Pep list and detail
3v-workspace/Data_converter pull request #273
Opened 2020-08-19 16:21 UTC by IegorSoboliev

2020-08-19 18:33 UTC, roman-tiukh requested changes

2020-08-19 18:33 UTC, roman-tiukh commented on business_register/serializers/company_serializers.py
> +            'id', 'name', 'company_type', 'edrpou', 'status', 'founder_of_count', 'is_closed',
i need short_name here.

2020-08-19 18:33 UTC, roman-tiukh commented on business_register/serializers/company_serializers.py
> +        fields = ('name', 'edrpou',)
id

2020-08-19 18:33 UTC, roman-tiukh commented on business_register/serializers/pep_serializers.py
> +    related_companies = CompanyLinkWithPepSerializer(many=True)
i offer to remove this fields from list serializer

2020-08-20 07:12 UTC, IegorSoboliev commented on business_register/serializers/company_serializers.py
> +            'id', 'name', 'company_type', 'edrpou', 'status', 'founder_of_count', 'is_closed',
restored

2020-08-20 07:14 UTC, IegorSoboliev commented on business_register/serializers/company_serializers.py
> +        fields = ('name', 'edrpou',)
added, but, please, explain, why we have to provide our internal ID in API?

2020-08-20 07:15 UTC, IegorSoboliev commented on business_register/serializers/pep_serializers.py
> +    related_companies = CompanyLinkWithPepSerializer(many=True)
no - we agreed with Liuba to provide in a list all info that we receive from ANTAC. No more, no less)

2020-08-20 07:18 UTC, roman-tiukh commented on business_register/serializers/company_serializers.py
> +        fields = ('name', 'edrpou',)
for query full info about the company
/company/id/

2020-08-20 07:21 UTC, roman-tiukh approved these changes

2020-08-20 07:29 UTC, merged