Made EndPoint model, serializer and part of the fixture
3v-workspace/Data_converter pull request #296
Opened 2020-09-09 09:09 UTC by IegorSoboliev

2020-09-09 10:51 UTC, IegorSoboliev commented on data_ocean/fixtures/register.json
> +  {
Is that a good idea to put it here?

2020-09-09 13:22 UTC, roman-tiukh requested changes

2020-09-09 13:22 UTC, roman-tiukh commented on data_ocean/fixtures/register.json
> +  {
its ok.

2020-09-09 13:22 UTC, roman-tiukh commented on data_ocean/fixtures/register.json
> +  {
1. Do it with all registers and all endpoints.
2. Then remove the list and retrieve fields from the Register model.
3. I think that the name_eng field is also needed.

2020-09-10 10:18 UTC, IegorSoboliev commented on data_ocean/fixtures/register.json
> +  {
done

2020-09-10 17:21 UTC, PyDev777 approved these changes

2020-09-10 18:34 UTC, roman-tiukh approved these changes

2020-09-10 18:34 UTC, merged