Made related persons links loader, refactored pep models and serializers
3v-workspace/Data_converter pull request #317
Opened 2020-10-08 11:53 UTC by IegorSoboliev

2020-10-08 14:23 UTC, roman-tiukh requested changes

2020-10-08 14:23 UTC, roman-tiukh commented on business_register/views/pep_views.py
> +# from rest_framework.permissions import AllowAny
?

2020-10-08 14:23 UTC, roman-tiukh commented on business_register/views/pep_views.py
> +    # permission_classes = [AllowAny]
?

2020-10-08 14:23 UTC, roman-tiukh commented on business_register/serializers/company_and_pep_serializers.py
> +    related_persons = PepShortestSerializer(many=True)
i think we need to implement this via RelatedPersonSerializer

2020-10-08 14:23 UTC, roman-tiukh commented on business_register/serializers/company_and_pep_serializers.py
> +
maybe need PepShortestSerializer here

2020-10-08 14:23 UTC, roman-tiukh commented on business_register/serializers/company_and_pep_serializers.py
> +            'related_persons', 'related_companies', 'check_companies',
why you uncomment this?

2020-10-08 14:24 UTC, roman-tiukh commented
first we need to decide what to do with the frontend

2020-10-09 09:23 UTC, IegorSoboliev commented on business_register/views/pep_views.py
> +# from rest_framework.permissions import AllowAny
for testing

2020-10-09 09:35 UTC, IegorSoboliev commented on business_register/views/pep_views.py
> +# from rest_framework.permissions import AllowAny
for testing

2020-10-09 09:35 UTC, IegorSoboliev commented on business_register/views/pep_views.py
> +    # permission_classes = [AllowAny]
for testing

2020-10-09 09:36 UTC, IegorSoboliev commented on business_register/serializers/company_and_pep_serializers.py
> +    related_persons = PepShortestSerializer(many=True)
done

2020-10-09 09:36 UTC, IegorSoboliev commented on business_register/serializers/company_and_pep_serializers.py
> +
done

2020-10-09 09:36 UTC, IegorSoboliev commented on business_register/serializers/company_and_pep_serializers.py
> +            'related_persons', 'related_companies', 'check_companies',
deleted at all

2020-10-12 18:18 UTC, roman-tiukh approved these changes

2020-10-12 18:18 UTC, merged