Made models for payment system
3v-workspace/Data_converter pull request #319
Opened 2020-10-13 12:23 UTC by IegorSoboliev

2020-10-13 14:03 UTC, criticus requested changes

2020-10-15 08:08 UTC, IegorSoboliev commented on payment_system/models.py
> +    info = models.CharField('інформація', max_length=500, null=True)
for the accountant (like 'note')

2020-10-15 08:09 UTC, IegorSoboliev commented on payment_system/models.py
> +    grace_period = models.DurationField('пільговий період', null=True)
done

2020-10-15 08:09 UTC, IegorSoboliev commented on payment_system/models.py
> +    duration = models.DurationField('тривалість')
done

2020-10-15 08:11 UTC, IegorSoboliev commented on payment_system/models.py
> +    requests_limit = models.IntegerField('максимальна кількість запитів')
done for the price. Zhenya wants to limit requests even for unlimited subscriptions - for stopping bugs on the client`s side

2020-10-15 08:12 UTC, IegorSoboliev commented on payment_system/models.py
> +    price = models.IntegerField('ціна')
done

2020-10-15 08:12 UTC, IegorSoboliev commented on payment_system/models.py
> +    name = models.CharField('назва', max_length=50, unique=True)
done

2020-10-15 14:17 UTC, criticus commented on payment_system/models.py
> +    grace_period = models.SmallIntegerField(null=True)
consider to use default=0

2020-10-15 14:18 UTC, criticus commented on payment_system/models.py
> +    info = models.CharField(max_length=500, null=True)
what is this field for?

2020-10-15 14:19 UTC, criticus commented on payment_system/migrations/0001_initial.py
> +                ('description', models.CharField(max_length=500, null=True, verbose_name='опис')),
consider to use latin names

2020-10-15 17:16 UTC, IegorSoboliev commented on payment_system/models.py
> +    info = models.CharField('інформація', max_length=500, null=True)
added a comment to the code

2020-10-15 17:16 UTC, IegorSoboliev commented on payment_system/models.py
> +    grace_period = models.SmallIntegerField(null=True)
done. For the duration set to 30

2020-10-15 17:17 UTC, IegorSoboliev commented on payment_system/migrations/0001_initial.py
> +                ('description', models.CharField(max_length=500, null=True, verbose_name='опис')),
replaced the migration

2020-10-15 18:19 UTC, criticus approved these changes
It looks good

2020-10-16 08:34 UTC, merged