Added methods to user for managing projects
3v-workspace/Data_converter pull request #322
Opened 2020-10-16 12:04 UTC by IegorSoboliev

2020-10-16 17:53 UTC, roman-tiukh requested changes
most of the methods are implemented in the user model, although this is not really necessary, since they do not interact with the user model. I think they don't belong in the user model.

2020-10-16 17:53 UTC, roman-tiukh commented on users/models.py
> +        new_token = Token.objects.create(user_id=self.id)
rest_framework token?

2020-10-16 17:53 UTC, roman-tiukh commented on users/models.py
> +        return Project.objects.filter(id=project_id).first()
redundant method

2020-10-16 17:53 UTC, roman-tiukh commented on users/models.py
> +        return project
this should be Project method

2020-10-16 17:53 UTC, roman-tiukh commented on users/models.py
> +            return None
raise Exception here

2020-10-16 17:53 UTC, roman-tiukh commented on users/models.py
> +            return None
and here

2020-10-16 17:53 UTC, roman-tiukh commented on users/models.py
> +        user = get_user_model().objects.filter(id=user_id).first()
you dont need to use get_user_model(), we have only one model for user - DataOceanUser

2020-10-16 17:53 UTC, roman-tiukh commented on users/models.py
> +        return project
this should be Project method

2020-10-16 17:53 UTC, roman-tiukh commented on users/models.py
> +        return Project.objects.filter(id=project_id).first()
why first()? use get() instead

2020-10-19 12:03 UTC, criticus commented on users/models.py
> +    def add_user_to_project(self, project_id, user_id):
consider moving under Project

2020-10-19 12:04 UTC, criticus commented on users/models.py
> +    def remove_user_from_project(self, project_id, user_id):
consider moving under Project

2020-10-19 13:22 UTC, IegorSoboliev commented on users/models.py
> +        new_token = Token.objects.create(user_id=self.id)
Do you have another suggestion?

2020-10-19 13:23 UTC, IegorSoboliev commented on users/models.py
> +        return project
moved

2020-10-19 13:28 UTC, IegorSoboliev commented on users/models.py
> +            return None
done with ObjectNotFound

2020-10-19 13:29 UTC, IegorSoboliev commented on users/models.py
> +            return None
done

2020-10-19 13:30 UTC, IegorSoboliev commented on users/models.py
> +        user = get_user_model().objects.filter(id=user_id).first()
we do have two models already

2020-10-19 13:31 UTC, IegorSoboliev commented on users/models.py
> +        return Project.objects.filter(id=project_id).first()
Then user can get an exception?

2020-10-19 13:32 UTC, IegorSoboliev commented on users/models.py
> +    def add_user_to_project(self, project_id, user_id):
done. But then every added user can add new users and so on

2020-10-19 13:32 UTC, IegorSoboliev commented on users/models.py
> +    def remove_user_from_project(self, project_id, user_id):
done with the same caution

2020-10-20 17:15 UTC, roman-tiukh requested changes

2020-10-20 17:15 UTC, roman-tiukh commented on payment_system/models.py
> +        self.deleted_at = now()
```suggestion
        self.deleted_at = timezone.now()
```
`now` is present in many libraries, need to more explicitly indicate where it is from

2020-10-20 17:15 UTC, roman-tiukh commented on payment_system/models.py
> +    custom = models.BooleanField(default=False)
blank=True
if you use `default`, you may set `blank=True`

2020-10-20 17:15 UTC, roman-tiukh commented on payment_system/models.py
>      price = models.SmallIntegerField(default=0)
blank=True

2020-10-20 17:15 UTC, roman-tiukh commented on payment_system/models.py
>      requests_limit = models.IntegerField('limit for API requests from the project', default=0)
blank=True

2020-10-20 17:15 UTC, roman-tiukh commented on payment_system/models.py
>      duration = models.SmallIntegerField(default=30)
blank=True

2020-10-20 17:15 UTC, roman-tiukh commented on payment_system/models.py
> +    grace_period = models.SmallIntegerField(null=True, default=30)
blank=True

2020-10-20 17:15 UTC, roman-tiukh commented on payment_system/models.py
>      users = models.ManyToManyField(settings.AUTH_USER_MODEL)
related_name?

2020-10-20 17:15 UTC, roman-tiukh commented on payment_system/models.py
>      disabled = models.BooleanField(default=False)
blank=True

2020-10-20 17:15 UTC, roman-tiukh commented on payment_system/models.py
> +    description = models.CharField(max_length=500, null=True, blank=True)
is good practice use for Char and Text fields `default='', null=False` with `blank=True`

2020-10-20 17:15 UTC, roman-tiukh commented on payment_system/models.py
> +    description = models.CharField(max_length=500, null=True, blank=True)
```suggestion
    description = models.CharField(max_length=500, blank=True, default='')
```

2020-10-20 17:15 UTC, roman-tiukh commented on payment_system/models.py
> +    description = models.CharField(max_length=500, null=True, blank=True)
maybe TextField?

2020-10-20 17:15 UTC, roman-tiukh commented on payment_system/models.py
> +    grace_period = models.SmallIntegerField(null=True, default=30)
null=True?

2020-10-20 17:15 UTC, roman-tiukh commented on payment_system/models.py
>                                       related_name='subscription_invoices')
`related_name`s?

2020-10-20 17:15 UTC, roman-tiukh commented on payment_system/models.py
> +    subscription = models.ForeignKey('Subscription', on_delete=models.CASCADE)
related_names?

2020-10-21 02:25 UTC, criticus commented on payment_system/models.py
> +        self.deleted_at = None
no need in `activated_at`, it will be the same as `created_at`

2020-10-21 08:53 UTC, IegorSoboliev commented on payment_system/models.py
> +    def add_user_to_project(self, user_id):
Why?

2020-10-21 08:54 UTC, IegorSoboliev commented on payment_system/models.py
> +    def remove_user_from_project(self, user_id):
Why?

2020-10-21 08:57 UTC, IegorSoboliev commented on payment_system/models.py
> +    def disable_project(self):
done

2020-10-21 08:58 UTC, IegorSoboliev commented on payment_system/models.py
> +    def activate_project(self):
done

2020-10-21 08:58 UTC, IegorSoboliev commented on payment_system/models.py
> +        return self
How do you set a new description if you want?

2020-10-21 09:00 UTC, IegorSoboliev commented on payment_system/models.py
> +        return self
done

2020-10-21 09:00 UTC, IegorSoboliev commented on payment_system/models.py
> +        return self
done

2020-10-21 09:01 UTC, IegorSoboliev commented on payment_system/models.py
> +        return self
done

2020-10-21 09:08 UTC, IegorSoboliev commented on payment_system/models.py
> +    subscriptions = models.ManyToManyField('Subscription', through=ProjectSubscription)
added

2020-10-21 09:09 UTC, IegorSoboliev commented on payment_system/models.py
> +from django.utils.timezone import now
(((

2020-10-21 09:09 UTC, IegorSoboliev commented on payment_system/models.py
> +        self.deleted_at = now()
Come on, in all other code we use now

2020-10-21 09:10 UTC, IegorSoboliev commented on payment_system/models.py
> +    custom = models.BooleanField(default=False)
we don`t need blank here at all

2020-10-21 09:11 UTC, IegorSoboliev commented on payment_system/models.py
>      price = models.SmallIntegerField(default=0)
?

2020-10-21 09:12 UTC, IegorSoboliev commented on payment_system/models.py
>      requests_limit = models.IntegerField('limit for API requests from the project', default=0)
?

2020-10-21 09:12 UTC, IegorSoboliev commented on payment_system/models.py
>      duration = models.SmallIntegerField(default=30)
?

2020-10-21 09:13 UTC, IegorSoboliev commented on payment_system/models.py
> +    grace_period = models.SmallIntegerField(null=True, default=30)
I think, we don`t need blank and null here at all

2020-10-21 09:15 UTC, IegorSoboliev commented on payment_system/models.py
>      disabled = models.BooleanField(default=False)
?

2020-10-21 09:18 UTC, IegorSoboliev commented on payment_system/models.py
> +    description = models.CharField(max_length=500, null=True, blank=True)
Done, but again, why we never did it before?

2020-10-21 09:18 UTC, IegorSoboliev commented on payment_system/models.py
> +    description = models.CharField(max_length=500, null=True, blank=True)
Why?

2020-10-21 09:19 UTC, IegorSoboliev commented on payment_system/models.py
> +    grace_period = models.SmallIntegerField(null=True, default=30)
?

2020-10-21 09:19 UTC, IegorSoboliev commented on payment_system/models.py
>                                       related_name='subscription_invoices')
like related+personS

2020-10-21 09:20 UTC, IegorSoboliev commented on payment_system/models.py
> +    subscription = models.ForeignKey('Subscription', on_delete=models.CASCADE)
added

2020-10-21 10:16 UTC, IegorSoboliev commented on payment_system/models.py
> +    def add_user_to_project(self, user_id):
add_user is not clear naming IMHO

2020-10-21 14:15 UTC, criticus commented on payment_system/models.py
> +    def add_user_to_project(self, user_id):
Project.add_user(User) seems pretty clear, doesn't it?

2020-10-21 14:15 UTC, criticus commented on payment_system/models.py
> +    def remove_user_from_project(self, user_id):
same as above

2020-10-21 14:16 UTC, criticus commented on payment_system/models.py
> +        self.deleted_at = now()
we should keep deleted_at as a base field but @roman-tiukh is right for disabling we need another field because it's not the same as deleting

2020-10-22 10:54 UTC, IegorSoboliev commented on payment_system/models.py
> +        return self
Deleted

2020-10-22 10:55 UTC, IegorSoboliev commented on payment_system/models.py
> +    def remove_user_from_project(self, user_id):
done

2020-10-22 10:55 UTC, IegorSoboliev commented on payment_system/models.py
> +    def add_user_to_project(self, user_id):
Ok, done

2020-10-22 11:13 UTC, IegorSoboliev commented on payment_system/models.py
> +        self.deleted_at = now()
changed disabled field to disabled_at, refactored methods

2020-10-22 13:33 UTC, roman-tiukh requested changes

2020-10-22 13:33 UTC, roman-tiukh commented on payment_system/models.py
> +    subscription = models.ForeignKey('Subscription', on_delete=models.CASCADE)
i don't see it

2020-10-22 13:33 UTC, roman-tiukh commented on payment_system/models.py
> +    def remove_user_(self, user):
```suggestion
    def remove_user(self, user):
```

2020-10-22 13:33 UTC, roman-tiukh commented on payment_system/models.py
> +        self.users.remove(user)
I don't understand the point in these methods, okay, let them be.
We can just do
```
project.users.add(user)
# or
project.users.remove(user)
```

2020-10-22 13:33 UTC, roman-tiukh commented on payment_system/models.py
i think we need extra prop `is_disabled`
```
@property
def is_disabled(self):
    return self.disabled_at is None
```
then we can check project for disabled
```
if project.is_disabled:
    do_something()
```

2020-10-22 13:33 UTC, roman-tiukh commented on payment_system/models.py
>      requests_limit = models.IntegerField('limit for API requests from the project', default=0)
if you set `default` you may set `blank=True`
they work in pairs

2020-10-22 13:33 UTC, roman-tiukh commented on users/models.py
> +        return new_project
now you can do here just 
```suggestion
    def create_project(self, project_name, project_description=None):
        return self.user_projects.create(
            name=project_name,
            token=generate_key(),
            description=project_description,
        )
```

2020-10-22 13:33 UTC, roman-tiukh commented on users/models.py
> +        return new_project
If you want, you can create token in `save()` method in Project. It will be nice.

2020-10-22 13:36 UTC, IegorSoboliev commented on payment_system/models.py
added

2020-10-22 13:41 UTC, IegorSoboliev commented on users/models.py
> +        return new_project
Please, explain the reason

2020-10-22 13:45 UTC, IegorSoboliev commented on payment_system/models.py
> +    def remove_user_(self, user):
fixed

2020-10-22 15:18 UTC, criticus commented on payment_system/models.py
> +    def add_user(self, user):
what happens if user was previously added?

2020-10-22 15:18 UTC, criticus commented on payment_system/models.py
> +    def remove_user(self, user):
what happens if user is not in the project?

2020-10-22 15:19 UTC, criticus commented on payment_system/models.py
> +        self.save(update_fields=['disabled_at'])
I'm confused. Is it `deleted_at` or `disabled_at`?

2020-10-22 15:33 UTC, roman-tiukh requested changes

2020-10-22 15:33 UTC, roman-tiukh commented on payment_system/models.py
> +        self.save(update_fields=['disabled_at'])
thanks @criticus . I missed this. here must be `self.disabled_at = ...`

2020-10-23 10:52 UTC, IegorSoboliev commented on payment_system/models.py
> +    def add_user(self, user):
nothing - https://docs.djangoproject.com/en/3.1/ref/models/relations/

2020-10-23 11:01 UTC, IegorSoboliev commented on payment_system/models.py
> +    def remove_user(self, user):
the same rule as above

2020-10-23 11:02 UTC, IegorSoboliev commented on payment_system/models.py
> +        self.save(update_fields=['disabled_at'])
sorry, fixed

2020-10-23 11:40 UTC, roman-tiukh approved these changes

2020-10-23 11:41 UTC, merged