Added filter and DB index for Pep code
3v-workspace/Data_converter pull request #325
Opened 2020-10-21 12:48 UTC by IegorSoboliev

2020-10-21 19:24 UTC, roman-tiukh requested changes
this should be implemented via @action in the viewset, we talked about this

2020-10-22 13:59 UTC, roman-tiukh requested changes

2020-10-22 13:59 UTC, roman-tiukh commented on business_register/views/pep_views.py
> +    permission_classes = [AllowAny]
you miss this line

2020-10-22 13:59 UTC, roman-tiukh commented on business_register/views/pep_views.py
> +from rest_framework.permissions import AllowAny
and this line

2020-10-22 13:59 UTC, roman-tiukh commented on business_register/models/pep_models.py
> +                                            db_index=True, null=True, blank=True)
null=True? Do we have peps without source_id?
It is very easy to remove `null=True` in the future.

2020-10-22 13:59 UTC, roman-tiukh commented on business_register/views/pep_views.py
> +    def retrieve_by_source_id(self, request, source_id):
Nice but method name is very long. Request will be:
```
/api/pep/retrieve_by_source_id/123/
```
if you can make this shortest it will be nice, like
```
/api/pep/source_id/123/
```

2020-10-22 14:05 UTC, roman-tiukh requested changes

2020-10-22 14:05 UTC, roman-tiukh commented on business_register/views/pep_views.py
> +        pep = get_object_or_404(self.queryset, source_id=source_id)
ohh i missed this

use self.get_queryset() instead of self.queryset
```suggestion
        pep = get_object_or_404(self.get_queryset(), source_id=source_id)
```

2020-10-22 14:20 UTC, IegorSoboliev commented on business_register/models/pep_models.py
> +                                            db_index=True, null=True, blank=True)
We do have DB already. Could you explain, what is the way to provide more than 40 k unique values?

2020-10-22 15:11 UTC, roman-tiukh commented on business_register/models/pep_models.py
> +                                            db_index=True, null=True, blank=True)
For this problem, we need to write our own migration.
I don't think there is time for that now. Then just remove the `blank = True`, this will prevent the creation of models without this field.

If in the future we have problems with this, then we will write a migration that first fills in all the blanks and then makes the field `null = False`

2020-10-23 11:44 UTC, IegorSoboliev commented on business_register/views/pep_views.py
> +        pep = get_object_or_404(self.queryset, source_id=source_id)
done

2020-10-23 11:45 UTC, IegorSoboliev commented on business_register/views/pep_views.py
> +    def retrieve_by_source_id(self, request, source_id):
added url_path

2020-10-23 11:56 UTC, roman-tiukh approved these changes

2020-10-23 11:56 UTC, roman-tiukh commented on business_register/models/pep_models.py
> +                                            db_index=True, null=True, blank=True)
yesterday I asked to leave `blank=False` here, but okay, approved

2020-10-23 11:59 UTC, merged