Project subscription methods
3v-workspace/Data_converter pull request #338
Opened 2020-11-02 13:00 UTC by IegorSoboliev

2020-11-02 14:24 UTC, roman-tiukh requested changes

2020-11-02 14:24 UTC, roman-tiukh commented on payment_system/models.py
> +        return project_subscription
this is not a classmethod, project_subscription its `self` in instance method

2020-11-02 14:24 UTC, roman-tiukh commented on payment_system/serializers/project_subscription_serializers.py
> +        return ProjectSubscription.disable(instance)
No... Its bad, update method is used to update the fields of an object, to deactivate the project, deactivate it inside the view inherited from APIView. In this case, no serializer is needed.

2020-11-02 14:24 UTC, roman-tiukh commented on payment_system/models.py
> +        return project_subscription
no need to build conditions here, just create a unique_together condition and when creating a uniqueness error, no need to return an object, we must inform users or the frontend about errors that occur.
Although if there can be several subscriptions, then the condition should not be at all

2020-11-03 07:23 UTC, IegorSoboliev commented on payment_system/models.py
> +        return project_subscription
done

2020-11-03 07:23 UTC, IegorSoboliev commented on payment_system/serializers/project_subscription_serializers.py
> +        return ProjectSubscription.disable(instance)
done

2020-11-03 07:26 UTC, IegorSoboliev commented on payment_system/models.py
> +        return project_subscription
Well, I guess the user should have a right to add a subscription he did use in the past

2020-11-03 14:27 UTC, roman-tiukh approved these changes

2020-11-03 14:28 UTC, merged