Added role field to DataOceanUser
3v-workspace/Data_converter pull request #339
Opened 2020-11-04 11:56 UTC by IegorSoboliev

2020-11-04 12:52 UTC, roman-tiukh requested changes
not in DataOceanUser...
User can be in many projects with different roles...
Do this in User2Project (m2m) model

2020-11-04 12:52 UTC, roman-tiukh commented on users/models.py
> +    ]
1. owner
2. member

---

Display names may be more readable...
project_initiator -> Owner
project_participant -> Member

-------------------------------------------------
`('PROJECT_INITIATOR', 'project_initiator'),` - here you dont pass variable, you pass simple string...

2020-11-04 12:52 UTC, roman-tiukh commented on users/models.py
> +    role = models.CharField(choices=ROLES, max_length=20, default='PROJECT_PARTICIPANT')
`default='PROJECT_PARTICIPANT'` -> `default=PROJECT_PARTICIPANT`

2020-11-04 12:52 UTC, roman-tiukh commented on users/models.py
> +    ]
read documentation about choices here pls
https://docs.djangoproject.com/en/3.1/ref/models/fields/#choices

2020-11-05 15:36 UTC, IegorSoboliev commented on users/models.py
> +    ]
done, thank you!

2020-11-05 15:45 UTC, IegorSoboliev commented on users/models.py
> +    role = models.CharField(choices=ROLES, max_length=20, default='PROJECT_PARTICIPANT')
Fixed

2020-11-06 09:01 UTC, roman-tiukh requested changes

2020-11-06 09:09 UTC, IegorSoboliev commented on payment_system/models.py
> +    role = models.CharField(choices=ROLES, max_length=20, default=PARTICIPANT)
Do you think, we can have a blank role?

2020-11-06 09:14 UTC, IegorSoboliev commented on payment_system/models.py
> +    role = models.CharField(choices=ROLES, max_length=20, default=PARTICIPANT)
added

2020-11-06 09:21 UTC, roman-tiukh approved these changes

2020-11-06 09:22 UTC, merged