Added user status field in UserProject
3v-workspace/Data_converter pull request #344
Opened 2020-11-10 11:15 UTC by IegorSoboliev

2020-11-10 20:19 UTC, roman-tiukh requested changes

2020-11-10 20:19 UTC, roman-tiukh commented on payment_system/models.py
> +        )
`self.user_projects.create(user=user)`

----
`self.users.add(user)` does not work now?

2020-11-11 12:25 UTC, IegorSoboliev commented on payment_system/models.py
> +        (REMOVED, "Removed"),
I think removed is better)

2020-11-11 13:20 UTC, IegorSoboliev commented on payment_system/models.py
> +        user_project = UserProject.objects.get(project=self, user=user)
done

2020-11-11 13:20 UTC, IegorSoboliev commented on payment_system/models.py
> +        user_project = UserProject.objects.get(project=self, user=user)
done

2020-11-11 13:23 UTC, IegorSoboliev commented on payment_system/models.py
> +        )
No. We can implement it like that:

user.user_projects.create(project=self)

But I think the first version looks more clear

2020-11-11 15:22 UTC, roman-tiukh approved these changes

2020-11-11 15:27 UTC, merged