Added total records to Dataset
3v-workspace/Data_converter pull request #352
Opened 2020-11-17 19:27 UTC by IegorSoboliev

2020-11-17 20:12 UTC, roman-tiukh requested changes

2020-11-17 20:12 UTC, roman-tiukh commented on data_converter/urls.py
> +                  ] + urlpatterns
why delete this?

2020-11-17 20:13 UTC, roman-tiukh commented on data_converter/urls.py
> +                  ] + urlpatterns
![image](https://user-images.githubusercontent.com/38906004/99442490-21586480-2922-11eb-8906-c3da17c2f807.png)

2020-11-18 10:49 UTC, IegorSoboliev commented on data_converter/urls.py
> +                  ] + urlpatterns
Restored

2020-11-18 12:09 UTC, roman-tiukh approved these changes

2020-11-18 13:00 UTC, merged