DO-723 add_users_columns_to_admin_panel
3v-workspace/Data_converter pull request #361
Opened 2020-11-26 15:04 UTC by Iva-khar

DO-723 add_users_columns_to_admin_panel

2020-11-26 15:23 UTC, roman-tiukh requested changes

2020-11-26 15:23 UTC, roman-tiukh commented on users/admin.py
> +                    'position', 'language', 'is_staff', 'is_active', 'is_superuser')
do all these fields really need to be displayed in a tabular view?

2020-11-26 15:23 UTC, roman-tiukh commented on users/admin.py
> +                   'position', 'language', 'is_staff', 'is_active', 'is_superuser')
it is not necessary to add all the fields to the list_filter, only the necessary ones, for text fields there is a search_fields option

2020-11-27 12:43 UTC, Iva-khar commented
View User page changed to 'read only' mode

2020-11-27 12:43 UTC, Iva-khar commented on users/admin.py
> +                    'position', 'language', 'is_staff', 'is_active', 'is_superuser')
- removed 'position' and 'is_superuser' fields from **list_display**;
- added 'id', 'date_joined', 'last_login', 'date_of_birth',  'organization', 'position', 'language', 'is_superuser' - all the fields from DB to **fieldsets**;
- removed unused **add_fieldsers** property

2020-11-27 12:43 UTC, Iva-khar commented on users/admin.py
> +                   'position', 'language', 'is_staff', 'is_active', 'is_superuser')
- removed all text fields except 'language' from **list_filter**;
- added 'last_name', 'first_name', 'organization' to **search_fields**;
- ordering changed to "by date_joined"

2020-11-27 13:04 UTC, roman-tiukh requested changes

2020-11-27 13:04 UTC, roman-tiukh commented on users/admin.py
> -    )
it may still be useful in the future

2020-11-27 13:58 UTC, Iva-khar commented on users/admin.py
> -    )
I thought it uses only with 'edit/add_new' options. Will return.

2020-11-27 14:09 UTC, roman-tiukh approved these changes

2020-11-27 16:54 UTC, merged

2020-11-27 22:14 UTC, criticus commented on users/admin.py
> +    def has_change_permission(self, request, obj=None):
please explain why it always returns False

2020-11-28 07:18 UTC, roman-tiukh commented on users/admin.py
> +    def has_change_permission(self, request, obj=None):
if we need to be able to change user data from the admin area, then we can add certain conditions.
Otherwise, this entry disables the ability to edit users from the admin panel.