Test architecture for custom Email Backend
3v-workspace/Data_converter pull request #362
Opened 2020-11-27 13:56 UTC by IegorSoboliev

2020-12-04 17:47 UTC, roman-tiukh commented on data_converter/settings.py
> +EMAIL_BACKEND = 'email_backend.DataConverterEmailBackend'
you need to move this file to a directory, for example `data_converter`

2020-12-04 17:47 UTC, roman-tiukh commented on email_backend.py
> +        sg = sendgrid.SendGridAPIClient(api_key=settings.SENDGRID_API_KEY)
```suggestion
        sg = sendgrid.SendGridAPIClient(api_key=self.api_key)
```

2020-12-04 17:47 UTC, roman-tiukh commented on email_backend.py
> +def send_template_mail(to_email, template, context, asynchronously=True):
need `subject`, and `from_email`

2020-12-04 17:47 UTC, roman-tiukh commented on email_backend.py
> +def send_template_mail(to_email, template, context, asynchronously=True):
```suggestion
def send_template_mail(to, subject, template, context, from_email=None, asynchronously=True):
```

2020-12-04 17:47 UTC, roman-tiukh commented on email_backend.py
> +    )
```suggestion
    email = EmailMessage(
        body=html,
        from_email=settings.DEFAULT_FROM_EMAIL,
        to=to,  # to_email must be a list
    )
    email.content_subtype = 'html'
```

2020-12-04 17:47 UTC, roman-tiukh commented on payment_system/templates/payment_system/new_subscription.html
> +{% extends "users/emails/_base.html" %}
move base template to general application `data_ocean/templates`

2020-12-04 17:47 UTC, roman-tiukh commented on payment_system/templates/payment_system/new_subscription.html
> +{% extends "users/emails/_base.html" %}
move this file to subdirectory `emails`

payment_system/templates/payment_system/**emails**/new_subscription.html

2020-12-04 17:53 UTC, roman-tiukh commented on data_converter/settings.py
> +EMAIL_BACKEND = 'email_backend.DataConverterEmailBackend'
this is not a DataConverterEmailBackend, its SendGridEmailBackend

2020-12-07 11:42 UTC, IegorSoboliev commented on data_converter/settings.py
> +EMAIL_BACKEND = 'email_backend.DataConverterEmailBackend'
No problem, renamed

2020-12-07 11:43 UTC, IegorSoboliev commented on email_backend.py
> +        sg = sendgrid.SendGridAPIClient(api_key=settings.SENDGRID_API_KEY)
done

2020-12-07 11:45 UTC, IegorSoboliev commented on email_backend.py
> +def send_template_mail(to_email, template, context, asynchronously=True):
added

2020-12-07 11:48 UTC, IegorSoboliev commented on email_backend.py
> +    )
added

2020-12-07 11:49 UTC, IegorSoboliev commented on payment_system/templates/payment_system/new_subscription.html
> +{% extends "users/emails/_base.html" %}
done

2020-12-07 14:28 UTC, roman-tiukh requested changes
`requirements.txt` must be more clear

2020-12-07 14:28 UTC, roman-tiukh commented on data_converter/email_backend.py
> +            sg.client.mail.send.post(request_body=mail.get())
need to handle unsuccessful sending attempts

2020-12-07 14:28 UTC, roman-tiukh commented on data_converter/email_backend.py
> +                       from_email=settings.DEFAULT_FROM_EMAIL):
```suggestion
                       from_email=None):
```

2020-12-07 14:28 UTC, roman-tiukh commented on data_converter/email_backend.py
> +    Thread(target=e_message.send()).start()
```suggestion
    if not asynchronously:
        e_message.send()
    else:
        # then we have toe use Celery here
        Thread(target=e_message.send).start()
```

2020-12-07 14:28 UTC, roman-tiukh commented on emails.py
> +
need to delete this file

2020-12-07 14:28 UTC, roman-tiukh commented on sendgrid.env
> +
what is this?

2020-12-07 14:28 UTC, roman-tiukh commented on requirements.txt
> +numpy==1.18.5
numpy?

2020-12-07 14:28 UTC, roman-tiukh commented on requirements.txt
> +coverage==5.2.1
coverage?

2020-12-08 10:08 UTC, IegorSoboliev commented on requirements.txt
> +coverage==5.2.1
this is for testing

2020-12-08 10:11 UTC, roman-tiukh commented on requirements.txt
> +coverage==5.2.1
But not in this PR.

2020-12-08 10:13 UTC, IegorSoboliev commented on requirements.txt
> +numpy==1.18.5
deleted

2020-12-08 10:13 UTC, IegorSoboliev commented on sendgrid.env
> +
a recommendation from SendGrid

2020-12-08 10:14 UTC, IegorSoboliev commented on emails.py
> +
I am going to put all EmailMessages here

2020-12-08 10:15 UTC, IegorSoboliev commented on data_converter/email_backend.py
> +            sg.client.mail.send.post(request_body=mail.get())
Is this good example from smtp.EmailBackend? `        try:
            self.connection.sendmail(from_email, recipients, message.as_bytes(linesep='\r\n'))
        except smtplib.SMTPException:
            if not self.fail_silently:
                raise
            return False
        return True
`

2020-12-08 10:18 UTC, IegorSoboliev commented on data_converter/email_backend.py
> +            sg.client.mail.send.post(request_body=mail.get())
And this is a SendGrid`s example `  import os
  from sendgrid import SendGridAPIClient
  from sendgrid.helpers.mail import (From, To, Subject, PlainTextContent, HtmlContent, Mail)
  from python_http_client import exceptions

  sendgrid_client = SendGridAPIClient(os.environ.get('SENDGRID_API_KEY'))
  from_email = From("help@twilio.com")
  to_email = To("ethomas@twilio.com")
  subject = Subject("Sending with Twilio SendGrid is Fun")
  plain_text_content = PlainTextContent("and easy to do anywhere, even with Python")
  html_content = HtmlContent("<strong>and easy to do anywhere, even with Python</strong>")
  message = Mail(from_email, to_email, subject, plain_text_content, html_content)
  try:
      response = sendgrid_client.send(message)
      print(response.status_code)
      print(response.body)
      print(response.headers)
  except exceptions.BadRequestsError as e:
      print(e.body)
      exit()`

2020-12-08 15:26 UTC, IegorSoboliev commented on payment_system/templates/payment_system/new_subscription.html
> +{% extends "users/emails/_base.html" %}
done with new one

2020-12-08 15:26 UTC, IegorSoboliev commented on requirements.txt
> +coverage==5.2.1
deleted

2020-12-09 15:18 UTC, roman-tiukh requested changes

2020-12-09 15:18 UTC, roman-tiukh commented on data_converter/email_backend.py
> +        Thread(target=e_message.send()).start()
forgot to fix here after previous comments
```suggestion
        Thread(target=e_message.send).start()
```

2020-12-09 15:18 UTC, roman-tiukh commented on data_converter/emails.py
> +                           'user_name': user_name,
**Just for information**:
in this function, we can accept the user object as the argument to, `to = [to_user.email,]`
and we can pass the user object to the template, then call `{{user.get_full_name}}` in the template

2020-12-09 15:18 UTC, roman-tiukh commented on data_converter/settings.py
> +
I think this option should be placed in settings_local.base.py

2020-12-09 15:24 UTC, IegorSoboliev commented on data_converter/settings.py
> +
That is not a local setting

2020-12-09 15:33 UTC, roman-tiukh commented on data_converter/settings.py
> +
what if we need to install another EmailBackend for the test server? Also for development on a local machine, I want to install the console EmailBackend

2020-12-10 10:13 UTC, IegorSoboliev commented on data_converter/email_backend.py
> +                logger.error(f'email {subject} was not sent to{email_message.to} because of {error}')
done

2020-12-10 10:29 UTC, IegorSoboliev commented on sendgrid.env
> +
deleted

2020-12-10 10:29 UTC, IegorSoboliev commented on requirements.txt
> +pandas==1.0.4
deleted

2020-12-10 10:30 UTC, IegorSoboliev commented on data_ocean/templates/data_ocean/emails/_base.html
> +        <a href=""><img src="mail.png" style="width: 20px;display: inline;" width="20" height="20"/></a>
Olexandr is going to fix that later

2020-12-10 10:31 UTC, IegorSoboliev commented on data_converter/emails.py
> +                       subject=EMAIL_CONFIRMATION,
deleted

2020-12-10 10:32 UTC, IegorSoboliev commented on data_converter/email_backend.py
> +                if response.status_code // 200 != 1:
Thank you, changed

2020-12-10 10:32 UTC, IegorSoboliev commented on data_converter/email_backend.py
> +                                   f'Status is {response.status_code}')
Ok, changed

2020-12-10 10:33 UTC, IegorSoboliev commented on data_converter/email_backend.py
> +        Thread(target=e_message.send()).start()
fixed

2020-12-10 10:35 UTC, IegorSoboliev commented on data_converter/emails.py
> +                           'user_name': user_name,
Let`s decide this when we will be defining places to call all send_..._message functions

2020-12-10 10:35 UTC, IegorSoboliev commented on data_converter/settings.py
> +
ok, changed

2020-12-11 07:06 UTC, roman-tiukh approved these changes

2020-12-11 07:08 UTC, roman-tiukh approved these changes

2020-12-11 07:08 UTC, roman-tiukh commented on data_converter/email_backend.py
> +            to_email = To(email_message.to)
?

2020-12-11 07:08 UTC, roman-tiukh commented on data_converter/email_backend.py
> +        # we have toe use Selery here
```suggestion
        # we have toe use Celery here
```

2020-12-11 18:05 UTC, roman-tiukh requested changes

2020-12-11 18:05 UTC, roman-tiukh commented on data_converter/emails.py
> +                       )
**Better practice ->**

in template: `{{project_subscription.expiring_date}} {{project_subscription.start_date}}` 

```suggestion
def send_new_invoice_message(user, invoice):
    send_template_mail(
        to=[user.email],
        subject='Новий рахунок',
        template='payment_system/emails/new_invoice.html',
        context={
            'user': user,
            'project_subscription': invoice.project_subscription,
            'invoice': invoice,
        }
)
```

2020-12-11 18:05 UTC, roman-tiukh commented on data_converter/emails.py
> +                       subject='Вас видалили із проєкту',
@criticus @IegorSoboliev 
Maybe need to add like `[DataOcean]` prefix to all subjects?

2020-12-14 09:07 UTC, IegorSoboliev commented on data_converter/emails.py
> +                       subject='Вас видалили із проєкту',
Could you, please, explain the idea more?

2020-12-14 09:12 UTC, IegorSoboliev commented on data_converter/emails.py
> +                       )
changed except invoice_link

2020-12-14 09:29 UTC, IegorSoboliev commented on data_converter/emails.py
> +                           'project_name': project_name
used get_full_name function, but leave the assignment in the context for the simpler code

2020-12-14 09:30 UTC, IegorSoboliev commented on data_converter/emails.py
> +                       )
changed

2020-12-14 09:30 UTC, IegorSoboliev commented on data_converter/email_backend.py
> +        # we have toe use Selery here
changed)

2020-12-14 13:47 UTC, roman-tiukh approved these changes

2020-12-14 14:13 UTC, merged