Rewrite Companies&FOP autoupdater for short source file
3v-workspace/Data_converter pull request #363
Opened 2020-11-27 15:00 UTC by PyDev777

2020-11-27 17:38 UTC, roman-tiukh requested changes

2020-11-27 17:38 UTC, roman-tiukh commented on data_ocean/downloader.py
> +        return True
-

2020-11-27 17:38 UTC, roman-tiukh commented on data_ocean/downloader.py
> +        return True
-

2020-11-30 16:12 UTC, PyDev777 commented on business_register/converter/fop.py
> +            if self.zip_required_file_sign not in i['url']:
Fixed

2020-11-30 16:12 UTC, PyDev777 commented on business_register/converter/company_converters/ukr_company.py
> +            if self.zip_required_file_sign not in i['url']:
Fixed

2020-11-30 16:20 UTC, roman-tiukh approved these changes

2020-11-30 16:23 UTC, merged