[DO-175] Add_historical_company_related_tables
3v-workspace/Data_converter pull request #365
Opened 2020-11-30 14:46 UTC by Iva-khar

[DO-175]  Create model HistoricalTerminationStarted
    - Create model HistoricalExchangeDataCompany
    - Create model HistoricalCompanyToPredecessor
    - Create model HistoricalCompanyToKved
    - Create model HistoricalBancruptcyReadjustment

2020-11-30 15:07 UTC, roman-tiukh requested changes
Any migration?

2020-12-01 13:10 UTC, Iva-khar commented
> Any migration?

Migration added

2020-12-01 18:39 UTC, roman-tiukh reviewed
@criticus @IegorSoboliev do we need this?

2020-12-23 15:41 UTC, roman-tiukh approved these changes

2021-01-12 12:41 UTC, merged