Added peps relationship category filter
3v-workspace/Data_converter pull request #388
Opened 2020-12-29 15:47 UTC by IegorSoboliev

2020-12-29 16:05 UTC, roman-tiukh requested changes

2020-12-29 16:05 UTC, roman-tiukh commented on business_register/serializers/company_and_pep_serializers.py
> +        return ToRelatedPersonLinkSerializer(queryset, many=True).data
dublicate code fragment, pls create a function or method for this task.

2020-12-30 14:20 UTC, IegorSoboliev commented on business_register/serializers/company_and_pep_serializers.py
> +        return ToRelatedPersonLinkSerializer(queryset, many=True).data
Ok, created

2020-12-30 14:50 UTC, roman-tiukh approved these changes

2020-12-30 14:56 UTC, merged