DO-175 company related historical company view
3v-workspace/Data_converter pull request #395
Opened 2021-01-12 12:47 UTC by Iva-khar

2021-01-13 10:00 UTC, roman-tiukh requested changes
1. order by version date `desc`
2. add filter by date (FilterSet + DateFromToRangeFilter)

2021-01-13 18:27 UTC, Iva-khar commented on business_register/views/company_views.py
> +        queryset = queryset.filter(*args, **kwargs)
1 & 2 - done. For the right naming I've change pk to company_id and that necessitated to override lookup_field in next comment

2021-01-13 18:28 UTC, Iva-khar commented on business_register/views/company_views.py
> +    lookup_field = 'company'
changed to `lookup_field = 'company_id'`

2021-01-15 07:36 UTC, roman-tiukh requested changes

2021-01-15 07:36 UTC, roman-tiukh commented on business_register/views/company_views.py
> +    ordering = ['-history_date']
why you use OrderingFilter here?
Just add order to queryset

2021-01-15 07:36 UTC, roman-tiukh commented on business_register/views/company_views.py
> +    ordering = ['-history_date']
if you need to have ordering filter add it to FilterSet

2021-01-15 10:05 UTC, Iva-khar commented on business_register/views/company_views.py
> +    ordering = ['-history_date']
+

2021-01-15 12:02 UTC, Iva-khar commented on business_register/views/company_views.py
> +    ordering = ['-history_date']
done

2021-01-15 12:14 UTC, roman-tiukh approved these changes

2021-01-15 12:41 UTC, merged