[DO-829] Generate PDF Invoice document v0.1
3v-workspace/Data_converter pull request #396
Opened 2021-01-12 13:10 UTC by Andrii17s

Still not done (blocked by [DO-792] and lack of seller_config data), but may be reviewed.

2021-01-13 08:57 UTC, roman-tiukh requested changes

2021-01-13 08:57 UTC, roman-tiukh commented on payment_system/templates/payment_system/invoice_det_uk.html
> +<p>Рахунок №{{company.id}} від {% load i18n %} {% language 'ukr' %} {{company.start_date|date:'d E Y'}} {% endlanguage %} p.</p>
move `load` to top

2021-01-13 08:57 UTC, roman-tiukh commented on payment_system/templates/payment_system/invoice_det_uk.html
> +<p>Рахунок №{{company.id}} від {% load i18n %} {% language 'ukr' %} {{company.start_date|date:'d E Y'}} {% endlanguage %} p.</p>
ukr? maybe uk?

2021-01-13 08:57 UTC, roman-tiukh commented on payment_system/templates/payment_system/invoice_detail.html
> +</html>
blank line at end of file

2021-01-13 08:57 UTC, roman-tiukh commented on payment_system/templates/payment_system/invoice_detail.html
> +<table class="table" id="invoice">
tabs

2021-01-13 08:57 UTC, roman-tiukh commented on payment_system/views.py
> +class InvoicePdfGenerator(generics.ListAPIView):
RetrieveAPIView

2021-01-13 08:57 UTC, roman-tiukh commented on payment_system/views.py
> +    def gener_pdf(request, pk):
```suggestion
    def retrieve(self, request, pk):
```

2021-01-13 08:57 UTC, roman-tiukh commented on payment_system/views.py
> +    queryset = Invoice
Invoice its not a queryset

2021-01-13 08:57 UTC, roman-tiukh commented on payment_system/views.py
> +        user = get_object_or_404(DataOceanUser.objects.all(), id=request.user.id)
redundant line

2021-01-13 08:57 UTC, roman-tiukh commented on payment_system/views.py
> +                                                                                  'pdv': pdv, 'user': user,
pdv -> vat

2021-01-13 08:57 UTC, roman-tiukh commented on payment_system/views.py
> +                summ = "one hryvnia' 00 kopiyok"
```suggestion
                summ = "one hryvnia 00 kopiyok"
```

2021-01-13 08:57 UTC, roman-tiukh commented on payment_system/views.py
> +            response.write(output.read())
try to write this with FileResponse and io.BytesIO

2021-01-19 07:04 UTC, roman-tiukh commented on payment_system/views.py
> +        qwerty = get_object_or_404(Invoice.objects.all(), id=pk)
qwerty?

2021-01-19 13:40 UTC, Andrii17s commented on payment_system/views.py
> +        qwerty = get_object_or_404(Invoice.objects.all(), id=pk)
Done

2021-01-19 13:52 UTC, Andrii17s commented on payment_system/views.py
> +        qwerty = get_object_or_404(Invoice.objects.all(), id=pk)
Done

2021-01-20 20:04 UTC, criticus commented on payment_system/models.py
> +        with open('payment_system/static/payment_system/credentials.txt') as cr_file:
consider moving this to settings

2021-01-20 20:05 UTC, criticus commented on payment_system/models.py
> +                    summ = 'one hryvnia 00 kopiyok'
better to replace with `elif` https://docs.python.org/3/tutorial/controlflow.html

2021-01-20 20:08 UTC, criticus commented on payment_system/models.py
> +    def get_pdf(self, request, user):
I think this method works better in `Invoice` class.  `Invoice.get_pdf()`. What do you think?

2021-01-21 06:50 UTC, roman-tiukh commented
@criticus its not actual PR, closed.

2021-01-21 06:50 UTC, closed without merging