[DO-945] source file fix
3v-workspace/Data_converter pull request #424
Opened 2021-01-22 10:42 UTC by Iva-khar

after 12.30.2020 the full UO source file from data.gov.ua needs to be decoded and replaced some symbols by this method

2021-01-22 11:34 UTC, roman-tiukh requested changes

2021-01-22 11:34 UTC, roman-tiukh commented on data_ocean/downloader.py
> +    def replace(self):
rename method
and move to UkrDownloader

2021-02-03 14:00 UTC, criticus commented
@Iva-khar what's status of this PR?

2021-02-03 16:11 UTC, Iva-khar commented
Waiting for the upgrade


On Wed, Feb 3, 2021 at 4:00 PM Lyuba <notifications@github.com> wrote:

> @Iva-khar <https://github.com/Iva-khar> what's status of this PR?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/3v-workspace/Data_converter/pull/424#issuecomment-772531447>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AORDHBLVCVRQGHSLFVA4LH3S5FJIXANCNFSM4WOJHYPQ>
> .
>

2021-02-12 15:06 UTC, Iva-khar commented on data_ocean/downloader.py
> +    def replace(self):
Done and added 2 new replaces

2021-02-16 12:43 UTC, roman-tiukh approved these changes

2021-02-16 12:44 UTC, merged