[DO-1105] United Register and Dataset
3v-workspace/Data_converter pull request #433
Opened 2021-01-28 10:03 UTC by IegorSoboliev

2021-01-28 10:22 UTC, roman-tiukh requested changes
need working views:
1. `api/company/<id>/`
2. `api/company/`
3. `api/company/<source>/<id>/` - retrieve company with filter by source
4. `api/company/<source>/` - list by source

2021-01-28 10:22 UTC, roman-tiukh commented on data_ocean/fixtures/register.json
> +      "api_detail": "/api/pep/{id}"
it is good practice to put a slash at the end of the url
```suggestion
      "api_list": "/api/pep/",
      "api_detail": "/api/pep/{id}/"
```

2021-01-28 10:44 UTC, IegorSoboliev commented on data_ocean/fixtures/register.json
> +      "api_detail": "/api/pep/{id}"
done

2021-01-28 11:31 UTC, roman-tiukh requested changes

2021-01-28 11:31 UTC, roman-tiukh commented on data_ocean/fixtures/register.json
> +      "api_detail": "/api/company/uk/{id}/"
![image](https://user-images.githubusercontent.com/38906004/106132792-11a09c00-616d-11eb-8bff-09f08bd4e498.png)

2021-01-29 15:17 UTC, roman-tiukh approved these changes

2021-01-29 15:17 UTC, merged