Added validation for boolean filters
3v-workspace/Data_converter pull request #499
Opened 2021-02-18 11:31 UTC by IegorSoboliev

2021-02-18 11:36 UTC, roman-tiukh requested changes

2021-02-18 11:36 UTC, roman-tiukh commented on business_register/filters.py
> +    is_dead = ValidationBooleanFilter()
remove this fields from `Meta.fields`

2021-02-18 11:36 UTC, roman-tiukh commented on data_ocean/filters.py
> +            )
add current  invalid value for message
```suggestion
            raise ValidationError({
                self.label: _(f'Invalid request parameter: "{value}", could be True, False, true, false, 1, 0'),
            })
```

2021-02-18 15:10 UTC, IegorSoboliev commented on business_register/filters.py
> +    is_dead = ValidationBooleanFilter()
done

2021-02-18 15:12 UTC, IegorSoboliev commented on data_ocean/filters.py
> +            )
value in form already is cleaned. So moved the whole process to a custom widget again

2021-02-19 14:01 UTC, roman-tiukh approved these changes

2021-02-19 14:01 UTC, merged