[DO-1253] Fix the issue with inappropriate symbols via register
3v-workspace/Data_converter pull request #504
Opened 2021-02-20 22:46 UTC by Andrii17s

Done, but maybe in wrong way

2021-02-22 08:19 UTC, roman-tiukh requested changes
wrong way.
1. Use regular expressions
2. Use RegexValidator from django.
3. RegexValidator can be connected to serializer field

2021-02-25 07:02 UTC, roman-tiukh requested changes

2021-02-25 07:02 UTC, roman-tiukh commented on users/serializers.py
> +            x = re.findall("[^a-z0-9-.'а-яії]", value)
`А-ЯёЁЇїІіЄєҐґ`
maybe need to add here whitespace

2021-03-02 19:00 UTC, Andrii17s commented
@roman-tiukh new version is ready

2021-03-03 17:47 UTC, roman-tiukh requested changes
![image](https://user-images.githubusercontent.com/38906004/109848388-e1ab5380-7c58-11eb-8697-d1eb1f9b055b.png)

2021-03-03 17:47 UTC, roman-tiukh commented on users/validators.py
> +validate_symbols = RegexValidator(
name_symbols_validator ?

2021-03-03 17:47 UTC, roman-tiukh commented on users/validators.py
> +validate_triple = RegexValidator(
two_in_row_validator ?

2021-03-03 17:47 UTC, roman-tiukh commented on users/locale/uk/LC_MESSAGES/django.po
> +#: users/models.py:110
?

2021-03-04 08:58 UTC, roman-tiukh approved these changes

2021-03-04 08:58 UTC, merged