[DO-927] {Not For Merge} Export pep to xlsx
3v-workspace/Data_converter pull request #513
Opened 2021-02-23 13:03 UTC by Iva-khar

2021-02-24 06:53 UTC, roman-tiukh requested changes

2021-02-24 06:53 UTC, roman-tiukh commented on business_register/views/pep_views.py
> +        after_date = datetime.strptime(request.GET['updated_at_after'], '%Y-%m-%d')
what hapen if get-parameters is wrong or not exists?

2021-02-24 06:53 UTC, roman-tiukh commented on business_register/views/pep_views.py
> +        worksheet_title = 'PEP'
why you create this variable?

2021-02-24 06:53 UTC, roman-tiukh commented on business_register/views/pep_views.py
> +        after_date = datetime.strptime(request.GET['updated_at_after'], '%Y-%m-%d')
If there are no parameters, then just return the data no older than 1 month

2021-02-24 06:53 UTC, roman-tiukh commented on business_register/views/pep_views.py
> +            return HttpResponse(export_file_path, content_type="text/plain")
else??

2021-02-24 06:53 UTC, roman-tiukh commented on business_register/views/pep_views.py
> +            return HttpResponse(export_file_path, content_type="text/plain")
Use `Response` from rest framework and return json

2021-02-24 06:53 UTC, roman-tiukh commented on business_register/views/pep_views.py
> +                                content_type="text/plain")
no need this validation

2021-02-24 06:53 UTC, roman-tiukh commented on business_register/views/pep_views.py
> +        export_file_path = ExportToXlsx().export(queryset, export_dict, worksheet_title)
... 
With such success you could not make a class, but make a function. You're not taking advantage of classes and OOP.
ExportToXlsx class is useless, only export method works.
```
ExportToXlsx().export(queryset, export_dict, worksheet_title)
```

2021-02-24 06:53 UTC, roman-tiukh commented on data_ocean/export.py
> +        s3.Bucket('pep-xlsx').put_object(Key=export_file_name, Body=data, ACL='public-read')
where is credentials?
They should located in settinds_local...
Is it possible?

2021-02-24 06:53 UTC, roman-tiukh commented on data_ocean/export.py
> +        with NamedTemporaryFile() as temp_file:
You dont need NamedTemporaryFile, use `io.BytesIO` instead.

2021-02-24 06:53 UTC, roman-tiukh commented on data_ocean/export.py
> +                    cell.value = repr(sell_value)
what is reason for catching **ALL** exceptions?

2021-02-24 06:53 UTC, roman-tiukh commented on data_ocean/export.py
> +                sell_value = getattr(record, column_properties[0])
sell value?
![image](https://user-images.githubusercontent.com/38906004/108959226-c9e23700-767c-11eb-9ff7-bd45f20b746e.png)

2021-02-24 06:53 UTC, roman-tiukh commented on data_ocean/export.py
> +        return settings.PEP_EXPORT_FOLDER_URL + export_file_name
is that full(absolute) link to file in S3?

2021-02-24 06:53 UTC, roman-tiukh commented on data_ocean/export.py
> +        return settings.PEP_EXPORT_FOLDER_URL + export_file_name
what is PEP_EXPORT_FOLDER_URL?

2021-02-24 06:53 UTC, roman-tiukh commented on README.md
> +Source: https://boto3.amazonaws.com/
![image](https://user-images.githubusercontent.com/38906004/108959524-30ffeb80-767d-11eb-9105-a3a9ce7140be.png)

2021-02-24 13:40 UTC, roman-tiukh requested changes
Generation and upload must be processed by Celery as background task.

2021-02-24 13:40 UTC, roman-tiukh commented on data_ocean/export.py
> +                    cell.value = repr(sell_value)
`repr`? Why not `str`?

2021-02-24 16:15 UTC, Iva-khar commented on business_register/views/pep_views.py
> +        worksheet_title = 'PEP'
For sending in `export()` -> for exel sheet naming & file naming

2021-02-24 17:39 UTC, Iva-khar commented on business_register/views/pep_views.py
> +            return HttpResponse(export_file_path, content_type="text/plain")
`if` deleted

2021-03-04 12:21 UTC, Iva-khar commented on business_register/views/pep_views.py
> +        after_date = datetime.strptime(request.GET['updated_at_after'], '%Y-%m-%d')
The get-parameters validation have been refactored

2021-03-04 12:23 UTC, Iva-khar commented on business_register/views/pep_views.py
> +        worksheet_title = 'PEP'
Rewrited with literal usage

2021-03-04 12:52 UTC, Iva-khar commented on business_register/views/pep_views.py
> +            return HttpResponse(export_file_path, content_type="text/plain")
done

2021-03-04 12:52 UTC, Iva-khar commented on business_register/views/pep_views.py
> +                                content_type="text/plain")
The get-parameters validation have been refactored

2021-03-04 12:54 UTC, Iva-khar commented on business_register/views/pep_views.py
> +        export_file_path = ExportToXlsx().export(queryset, export_dict, worksheet_title)
Will refactor after the new export views appears..

2021-03-04 14:43 UTC, Iva-khar commented on data_ocean/export.py
> +        s3.Bucket('pep-xlsx').put_object(Key=export_file_name, Body=data, ACL='public-read')
done

2021-03-04 15:52 UTC, Iva-khar commented on data_ocean/export.py
> +        with NamedTemporaryFile() as temp_file:
done

2021-03-04 16:41 UTC, Iva-khar commented on data_ocean/export.py
> +                    cell.value = repr(sell_value)
(try-exept) - deleted

2021-03-04 16:41 UTC, Iva-khar commented on data_ocean/export.py
> +                sell_value = getattr(record, column_properties[0])
fixed

2021-03-04 17:05 UTC, Iva-khar commented on README.md
> +Source: https://boto3.amazonaws.com/
Readmy for expord has deleted

2021-03-04 17:06 UTC, Iva-khar commented
> Generation and upload must be processed by Celery as background task.

done

2021-03-04 17:13 UTC, Iva-khar commented
accidentally deleted repited comment "repr? Why not str?"

2021-03-05 09:58 UTC, roman-tiukh requested changes
![image](https://user-images.githubusercontent.com/38906004/110099500-0b27c480-7daa-11eb-98fc-d9859ea112c8.png)

2021-03-15 15:18 UTC, Iva-khar commented on business_register/views/pep_views.py
> +        return Response(data, status=200)
done

2021-03-15 18:51 UTC, Iva-khar commented on business_register/tasks.py
> +    return ExportToXlsx().export(query, export_dict, model_name)
done

2021-03-15 18:52 UTC, Iva-khar commented on business_register/views/pep_views.py
> +            query = self.filter_queryset(self.get_queryset()).query.__str__()
ommited

2021-03-15 18:52 UTC, Iva-khar commented on business_register/views/pep_views.py
> +            query = SearchFilter().filter_queryset(request, queryset, self).query.__str__()
ommmited

2021-03-16 08:16 UTC, roman-tiukh commented on business_register/emails.py
> +    user = DataOceanUser(id=user_id)
...

2021-03-16 08:16 UTC, roman-tiukh commented on business_register/emails.py
> +        subject='Generation of .xlsx export file completed',
At end it must be localized

2021-03-16 08:16 UTC, roman-tiukh commented on data_ocean/export.py
> +        export_filterset_class = getattr(filters, model_name + 'ExportFilterSet')
i think its wrong way...

2021-03-16 18:57 UTC, Iva-khar commented on data_ocean/export.py
> +        export_filterset_class = getattr(filters, model_name + 'ExportFilterSet')
refactored

2021-03-16 18:58 UTC, Iva-khar commented on business_register/emails.py
> +    user = DataOceanUser(id=user_id)
fixed

2021-03-17 08:02 UTC, Iva-khar commented on business_register/emails.py
> +        subject='Generation of .xlsx export file completed',
In another PR.

2021-03-19 08:48 UTC, roman-tiukh requested changes
no generated messages for localization

2021-03-19 08:48 UTC, roman-tiukh commented on business_register/forms.py
> +                'updated_at': ['Period for updated_at is not provided.']
localization

2021-03-19 08:48 UTC, roman-tiukh commented on business_register/forms.py
> +                'updated_at': ['Period for updated_at not matches restrictions.']
localization

2021-03-24 06:33 UTC, roman-tiukh commented on data_ocean/locale/uk/LC_MESSAGES/django.po
> +msgstr "Скачати файл"
diwnload it -> скачати файл?

2021-03-24 06:33 UTC, roman-tiukh commented on data_ocean/locale/uk/LC_MESSAGES/django.po
> +msgstr "Файл формату .xlsx за Вашим запитом сгенеровано."
Now You may?

2021-03-24 06:33 UTC, roman-tiukh commented on data_ocean/locale/uk/LC_MESSAGES/django.po
> +#: templates/data_ocean/emails/_base.html:48
data_ocean markers was deleted?

2021-03-24 06:33 UTC, roman-tiukh commented on data_ocean/export.py
> +                export_url
`export_url` it's not a continue for message. The link is defined for clicking on the message

2021-03-24 06:33 UTC, roman-tiukh commented on requirements.txt
> +importlib-metadata==3.7.3
its for boto3?

2021-03-24 10:44 UTC, Iva-khar commented on data_ocean/locale/uk/LC_MESSAGES/django.po
> +msgstr "Скачати файл"
changed

2021-03-24 10:44 UTC, Iva-khar commented on data_ocean/locale/uk/LC_MESSAGES/django.po
> +msgstr "Файл формату .xlsx за Вашим запитом сгенеровано."
changed

2021-03-24 10:45 UTC, Iva-khar commented on data_ocean/locale/uk/LC_MESSAGES/django.po
> +#: templates/data_ocean/emails/_base.html:48
Yes, by the `makemessages -a`

2021-03-24 10:55 UTC, Iva-khar commented on data_ocean/export.py
> +                export_url
changed

2021-03-24 10:56 UTC, Iva-khar commented on requirements.txt
> +importlib-metadata==3.7.3
for boto3 or for openxlsx

2021-03-24 14:06 UTC, roman-tiukh requested changes

2021-03-24 14:06 UTC, roman-tiukh commented on requirements.txt
> +typing-extensions==3.7.4.3
unused

2021-03-24 14:06 UTC, roman-tiukh commented on requirements.txt
> +zipp==3.4.1
unused

2021-03-24 14:06 UTC, roman-tiukh commented on requirements.txt
> +jdcal==1.4.1
unused

2021-03-24 14:06 UTC, roman-tiukh commented on requirements.txt
> +importlib-metadata==3.7.3
unused

2021-03-24 15:53 UTC, Iva-khar commented on requirements.txt
> +openpyxl==3.0.5
added

2021-03-24 16:56 UTC, roman-tiukh approved these changes

2021-03-24 16:56 UTC, merged