DO-1320 Update RATU converter
3v-workspace/Data_converter pull request #564
Opened 2021-03-10 12:34 UTC by Hedgehog18

The file from February 9 was flooded into the database, after that the file from March 2 was transferred to the converter.
After working out the converter:
District - nothing deleted
City - 616 records tagged "deleted_at"
City District - 393 records tagged "deleted_at"
Street - 1395 records tagged "deleted_at"
Converter run time is approximately 7 minutes.

2021-03-10 12:40 UTC, roman-tiukh commented
@Iva-khar @IegorSoboliev review pls

2021-03-10 13:34 UTC, Iva-khar requested changes

2021-03-10 13:34 UTC, Iva-khar commented on location_register/converter/ratu.py
> +            if self.outdated_districts_dict.get(district_code):
It's redudance checking

2021-03-10 13:34 UTC, Iva-khar commented on location_register/converter/ratu.py
> +            if self.outdated_cities_dict.get(city_code):
the same

2021-03-10 13:34 UTC, Iva-khar commented on location_register/converter/ratu.py
> +            if self.outdated_streets_dict.get(street_code):
the same

2021-03-10 13:34 UTC, Iva-khar commented on location_register/converter/ratu.py
> +            if self.outdated_citydistricts_dict.get(citydistrict_code):
the same

2021-03-10 13:34 UTC, Iva-khar commented on location_register/converter/ratu.py
>                  name=street_name,
What about the same street names in different some nemes cities? line 123

2021-03-10 13:34 UTC, Iva-khar commented on location_register/converter/ratu.py
>              )
line 102 `citydistrict_code = city.name + citydistrict_name` is it unic parametr?

2021-03-10 13:38 UTC, Hedgehog18 commented on location_register/converter/ratu.py
> +            if self.outdated_districts_dict.get(district_code):
Without this check there is an error, yesterday with Egor this moment was discussed

2021-03-10 13:38 UTC, Hedgehog18 commented on location_register/converter/ratu.py
> +            if self.outdated_streets_dict.get(street_code):
Without this check there is an error, yesterday with Egor this moment was discussed

2021-03-10 13:38 UTC, Hedgehog18 commented on location_register/converter/ratu.py
> +            if self.outdated_citydistricts_dict.get(citydistrict_code):
Without this check there is an error, yesterday with Egor this moment was discussed

2021-03-10 13:42 UTC, Hedgehog18 commented on location_register/converter/ratu.py
>                  name=street_name,
We refer to the "code": street_code = city.name + street_name.
If I understood the question correctly.

2021-03-10 14:13 UTC, IegorSoboliev commented on location_register/converter/ratu.py
> +
Actually, we have no reason to measure a length here

2021-03-10 14:41 UTC, Iva-khar commented on location_register/converter/ratu.py
> +            if self.outdated_citydistricts_dict.get(citydistrict_code):
What error? Why error?

2021-03-10 14:55 UTC, roman-tiukh commented on location_register/converter/ratu.py
> +            if self.outdated_citydistricts_dict.get(citydistrict_code):
```
d = {'hello': 1}
del d['as']
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
KeyError: **'as'**
```

2021-03-10 14:55 UTC, roman-tiukh commented on location_register/converter/ratu.py
> +            if self.outdated_citydistricts_dict.get(citydistrict_code):
```
d = {'hello': 1}
del d['as']
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
KeyError: **'as'**
```

2021-03-10 14:56 UTC, roman-tiukh approved these changes

2021-03-10 15:14 UTC, Iva-khar commented on location_register/converter/ratu.py
>                  name=street_name,
Not. It have to be unic.

2021-03-10 15:26 UTC, Iva-khar requested changes

2021-03-10 15:26 UTC, Iva-khar commented on location_register/converter/ratu.py
>              )
Must be `citydistrict_code = region.name + city.name + citydistrict_name` for sure

2021-03-10 15:26 UTC, Iva-khar commented on location_register/converter/ratu.py
>                  name=street_name,
Must be `street_code = region.name + district.name + city.name + citydistrict_name` for unic

2021-03-11 11:51 UTC, Hedgehog18 commented
After testing the updated converter, the results changed:
CityDistrict: 519 "deleted" (old result - 393)
Street: 1636 "deleted" (old result - 1395)

2021-03-11 12:33 UTC, Iva-khar requested changes

2021-03-11 12:33 UTC, Iva-khar commented on location_register/converter/ratu.py
> +        street_code = region.name + district_name + city.name + street_name
I would add also sitydistrict.name here

2021-03-11 12:33 UTC, Iva-khar commented on location_register/converter/ratu.py
> +            if self.outdated_districts_dict.get(district_code):
I return to my mean that it's redudance checking. When you have unic field 'code' error with missing key never happens. You have wrong 'code' if it happens

2021-03-11 12:33 UTC, Iva-khar commented on location_register/converter/ratu.py
> +            if self.outdated_cities_dict.get(city_code):
the same

2021-03-11 12:33 UTC, Iva-khar commented on location_register/converter/ratu.py
> +            if self.outdated_citydistricts_dict.get(citydistrict_code):
I return to my mean that it's redudance checking. When you have unic field 'code' error with missing key never happens. You have wrong 'code' if it happens

2021-03-11 12:33 UTC, Iva-khar commented on location_register/converter/ratu.py
> +            if self.outdated_streets_dict.get(street_code):
the same

2021-03-12 14:58 UTC, Iva-khar requested changes

2021-03-12 14:58 UTC, Iva-khar commented on location_register/converter/ratu.py
> +            if self.outdated_streets_dict.get(street_code):
test without this cheking

2021-03-15 11:17 UTC, Iva-khar approved these changes

2021-03-15 11:48 UTC, merged