[ DO-1240 ] add and validate fields to users model
3v-workspace/Data_converter pull request #617
Opened 2021-03-22 18:19 UTC by Alexandr8854

add and validate fields to users model

2021-03-22 18:23 UTC, Alexandr8854 commented
@roman-tiukh I hope I did everything right

2021-03-23 06:42 UTC, roman-tiukh requested changes
migrations?

2021-03-23 06:42 UTC, roman-tiukh commented on users/serializers.py
> +            if data.get('iban') == '':
bad condition
```suggestion
            if data.get('iban'):
```

2021-03-23 06:42 UTC, roman-tiukh commented on users/serializers.py
> +        if data.get('persone_status') == 'fop' and 'legal_entity':
broken condition
```suggestion
        if data.get('persone_status') in ('fop', 'legal_entity'):
```

2021-03-23 06:42 UTC, roman-tiukh commented on users/validators.py
> +                                   message = _('This field must contain 29 characters, numbers and Latin'))
```suggestion
                                   message = _('Wrong IBAN format'))
```

2021-03-23 06:42 UTC, roman-tiukh commented on users/validators.py
> +validate_iban = RegexValidator(regex='^UA\\d{8}[A-Z0-9]{19}$',
is this valid regex?

2021-03-23 06:42 UTC, roman-tiukh commented on users/validators.py
> +validate_edrpou = RegexValidator(regex='^[0-9]{8}$',
```suggestion
validate_edrpou = RegexValidator(regex='^\d{8}$',
```

2021-03-23 06:42 UTC, roman-tiukh commented on users/serializers.py
> +                raise serializers.ValidationError(_("enter registration address please"))
you 3 times check the same condition

2021-03-23 06:42 UTC, roman-tiukh commented on users/serializers.py
> +        if data.get('persone_status') == 'legal_entity':
Use constants from model 
```
DataOceanUser.LEGAL_ENTITY
```

2021-03-23 06:42 UTC, roman-tiukh commented on users/validators.py
> +validate_iban = RegexValidator(regex='^UA\\d{8}[A-Z0-9]{19}$',
```suggestion
iban_validator = RegexValidator(regex='^UA\\d{8}[A-Z0-9]{19}$',
```

2021-03-23 06:42 UTC, roman-tiukh commented on users/validators.py
> +validate_edrpou = RegexValidator(regex='^[0-9]{8}$',
```suggestion
edrpou_validator = RegexValidator(regex='^[0-9]{8}$',
```

2021-03-23 06:42 UTC, roman-tiukh commented on users/serializers.py
> +              raise serializers.ValidationError(_("enter iban please"))
you missed field name 
```suggestion
              raise serializers.ValidationError({'iban': _("This field is required for company or FOP"}))
```

2021-03-23 06:42 UTC, roman-tiukh commented on users/models.py
> +    can_admin_payment_system = models.BooleanField(blank=True, default=False)
wrong changes

2021-03-23 06:42 UTC, roman-tiukh commented on users/models.py
> +    )
move this to the top of model

2021-03-23 06:42 UTC, roman-tiukh commented on users/models.py
> +from django.core.exceptions import ValidationError
unused import

2021-03-23 06:42 UTC, roman-tiukh commented on users/serializers.py
> +        """
short docstring can be located in one line
```suggestion
        """ validate fop and legal_entity fields """
```

2021-03-26 13:58 UTC, closed without merging