[DO - 1383] Create Daily payments report logic
3v-workspace/Data_converter pull request #622
Opened 2021-03-23 15:46 UTC by Andrii17s

2021-04-01 07:01 UTC, roman-tiukh requested changes
Attach a screenshot to the PR.
What the report looks like

2021-04-01 07:01 UTC, roman-tiukh commented on payment_system/emails.py
> +def create_report(daily_report: 'InvoiceDailyReport'):
you declare type `InvoiceDailyReport` but pass string on call
```
emails.create_report(message_text)
```

2021-04-01 07:01 UTC, roman-tiukh commented on payment_system/emails.py
> +        template='payment_system/emails/new_daily_report.html',
```suggestion
        template='payment_system/emails/daily_report.html',
```

2021-04-05 13:31 UTC, Andrii17s commented
![Screenshot from 2021-04-17 17-57-58](https://user-images.githubusercontent.com/75915283/113579041-67da0180-962c-11eb-867b-cace7ea75af6.png)

2021-04-08 07:59 UTC, roman-tiukh requested changes

2021-04-08 13:07 UTC, Andrii17s commented
![Uploading Screenshot from 2021-04-08 15-59-44.png…]()

2021-04-12 13:20 UTC, Andrii17s commented
![Screenshot from 2021-04-12 16-18-30](https://user-images.githubusercontent.com/75915283/114400765-f7426000-9baa-11eb-8c8d-bcc4b824d97a.png)

2021-04-12 13:31 UTC, roman-tiukh approved these changes

2021-04-12 13:32 UTC, merged