[DO-1687] Upgrade report for 'in progress' updates
3v-workspace/Data_converter pull request #729
Opened 2021-04-21 10:01 UTC by Iva-khar

Add status for 'in progress' register updates

2021-04-22 11:25 UTC, roman-tiukh requested changes

2021-04-22 11:25 UTC, roman-tiukh commented on data_ocean/converter.py
> +                    return False
you cannot `return` after `raise`...

2021-04-22 11:25 UTC, roman-tiukh commented on data_ocean/converter.py
> +                    return False
are you tested this changes?

2021-04-22 12:04 UTC, Iva-khar commented on data_ocean/converter.py
> +                    return False
Not for exept. I remove `raise`, it needn't now.

2021-04-26 07:16 UTC, roman-tiukh requested changes
@IegorSoboliev please review this PR

2021-04-26 08:44 UTC, IegorSoboliev commented on business_register/converter/pep.py
> +        if converter.process():
I don`t think we need changes in this converter at all

2021-05-06 10:04 UTC, Iva-khar commented on business_register/converter/pep.py
> +        if converter.process():
Removed all changes in pep.py

2021-05-06 10:05 UTC, Iva-khar commented on business_register/converter/pep.py
>              self.report.save()
The same.

2021-05-06 10:05 UTC, Iva-khar commented on business_register/converter/pep.py
> +                logger.info(f'{self.reg_name}: Update finished unsuccessfully. See update_message')
The same.

2021-05-06 10:05 UTC, Iva-khar commented on business_register/converter/pep.py
> +            self.report.save()
The same.

2021-05-07 06:23 UTC, roman-tiukh approved these changes

2021-05-07 09:40 UTC, merged