[DO-983] Export fop
3v-workspace/Data_converter pull request #765
Opened 2021-05-08 10:44 UTC by Iva-khar

By api like: `/api/fop/xlsx/?registration_date_after=2021-03-10&registration_date_before=2021-04-05&status=2` uploads .xlsx file to s3 like:
![Screenshot from 2021-05-08 13-35-19](https://user-images.githubusercontent.com/60961669/117536340-29f14400-b003-11eb-977b-a7181ea95dba.png)

2021-05-11 06:20 UTC, roman-tiukh requested changes
Duplicated code
![image](https://user-images.githubusercontent.com/38906004/117767409-935a9800-b239-11eb-8718-c5a4e2bd8e91.png)

2021-05-11 06:20 UTC, roman-tiukh commented on data_ocean/export.py
> +                    cell_value = str(cell_value)
Nope, its bad. You have other types what can be supported with openpyxl, for example `timedelta`.

2021-05-11 06:20 UTC, roman-tiukh commented on business_register/views/fop_views.py
> +        from django.utils.translation import gettext_lazy as _
move this import to top

2021-05-11 14:08 UTC, Iva-khar commented
> Duplicated code
> ![image](https://user-images.githubusercontent.com/38906004/117767409-935a9800-b239-11eb-8718-c5a4e2bd8e91.png)

Different fields. Messages chenged (also different)

2021-05-12 11:01 UTC, Iva-khar commented
> Duplicated code
> ![image](https://user-images.githubusercontent.com/38906004/117767409-935a9800-b239-11eb-8718-c5a4e2bd8e91.png)

Maked abstract form

2021-05-12 11:26 UTC, Iva-khar commented on data_ocean/export.py
> +                    cell_value = str(cell_value)
Rewrited.

2021-05-12 11:26 UTC, Iva-khar commented on business_register/views/fop_views.py
> +        from django.utils.translation import gettext_lazy as _
done

2021-05-13 14:38 UTC, roman-tiukh approved these changes

2021-05-13 16:28 UTC, Iva-khar commented on data_ocean/export.py
> +                elif isinstance(cell_value, (Authority, Status)):
of course

2021-05-13 17:04 UTC, Iva-khar commented on data_ocean/export.py
> +                elif isinstance(cell_value, (Authority, Status)):
done

2021-05-13 17:05 UTC, merged