DO-1776 Make method for finding city of registration
3v-workspace/Data_converter pull request #773
Opened 2021-05-12 12:28 UTC by EmmaSamoilova

2021-05-12 13:16 UTC, IegorSoboliev requested changes

2021-05-12 13:16 UTC, IegorSoboliev commented on business_register/converter/declaration.py
> +                city_of_registration = ratu_region
There will be ValueError. Maybe, good idea is to store both cities as City object

2021-05-12 13:16 UTC, IegorSoboliev commented on business_register/converter/declaration.py
> +            elif region and city:
You can retrieve an object with None district field

2021-05-13 09:04 UTC, IegorSoboliev approved these changes

2021-05-13 09:04 UTC, IegorSoboliev commented on business_register/converter/declaration.py
> +            if region == city:
Do you mean Kyiv and Sevastopol? Are you sure there will be no other matches?

2021-05-13 09:04 UTC, IegorSoboliev commented on business_register/converter/declaration.py
> +            elif region and city:
No, I mean you can filter lile this 
```
RatuCity.objects.filter(
                        name=city, region_id=ratu_region.id, district_id=ratu_district.id
                    ).first()
```
even with district_id = Null

2021-05-13 14:29 UTC, roman-tiukh approved these changes

2021-05-13 14:29 UTC, merged