[DO-1229] Full word filter
3v-workspace/Data_converter pull request #775
Opened 2021-05-13 11:37 UTC by Iva-khar

Before:
![2df77b0d-4ea8-4281-8b09-6a2eeadcc9cb](https://user-images.githubusercontent.com/60961669/118120437-90f26c80-b3f8-11eb-816e-b7dbdf61e31a.png)
After:
![Screenshot from 2021-05-13 14-15-24](https://user-images.githubusercontent.com/60961669/118120460-9b146b00-b3f8-11eb-950c-a3067838eda6.png)

2021-05-13 12:13 UTC, roman-tiukh reviewed
![image](https://user-images.githubusercontent.com/38906004/118124029-b46be600-b3fd-11eb-8e05-f434801bd268.png)

2021-05-14 11:09 UTC, Iva-khar commented
Writed self FullWordSearchFilter

2021-05-17 07:37 UTC, roman-tiukh requested changes

2021-05-17 07:37 UTC, roman-tiukh commented on business_register/filters.py
> +        return [request.query_params.get(self.search_param, '')]
where? 
```python
params = params.replace('\x00', '')
```
its useful

2021-05-17 09:30 UTC, Iva-khar commented on business_register/filters.py
> +        return [request.query_params.get(self.search_param, '')]
Added

2021-05-17 10:51 UTC, roman-tiukh approved these changes

2021-05-17 11:36 UTC, merged