Added field for Ukrainian names to Country model
3v-workspace/Data_converter pull request #784
Opened 2021-05-15 09:17 UTC by EmmaSamoilova

2021-05-17 05:47 UTC, roman-tiukh requested changes
let's use suffixes `_en` and `_uk`

2021-05-17 11:44 UTC, IegorSoboliev approved these changes

2021-05-18 05:51 UTC, roman-tiukh requested changes

2021-05-18 05:51 UTC, roman-tiukh commented on location_register/management/commands/add_country_ukrainian_name.py
> +        '10': ['ангілья', 'anguilla'],
??? why numbers?
```
{
  'ukraine': 'україна',
  ...
}
```

2021-05-18 05:51 UTC, roman-tiukh commented on location_register/models/address_models.py
> +    name_uk = models.CharField(_('ukrainian name'), max_length=100, default='')
unique=True?

2021-05-18 06:08 UTC, EmmaSamoilova commented on location_register/management/commands/add_country_ukrainian_name.py
> +        '10': ['ангілья', 'anguilla'],
These numbers are only needed to identify countries in the register of dictations. There is no country name in the dictations register, only their id in the database. To understand what these id mean, Iegor threw me a doc file with an id and a name. In order not to duplicate similar dictionaries twice, I combined them and import this dictionary into the declaration converter.

2021-05-18 06:11 UTC, EmmaSamoilova commented on location_register/models/address_models.py
> +    name_uk = models.CharField(_('ukrainian name'), max_length=100, default='')
default='' will there be an error?

2021-05-18 06:47 UTC, IegorSoboliev commented on location_register/management/commands/add_country_ukrainian_name.py
> +        '10': ['ангілья', 'anguilla'],
I think we need this only in the declaration module

2021-05-18 07:37 UTC, roman-tiukh commented on location_register/models/address_models.py
> +    name_uk = models.CharField(_('ukrainian name'), max_length=100, default='')
in this case we can use `null=True, default=None, unique=True`

2021-05-18 08:42 UTC, roman-tiukh approved these changes

2021-05-18 08:45 UTC, roman-tiukh commented on location_register/management/commands/add_country_ukrainian_name.py
> +                logger.info(f'New country {country_en}')
self.stdout

2021-05-18 09:11 UTC, roman-tiukh approved these changes

2021-05-18 09:12 UTC, merged