Changed find_city in DeclarationConverter and added find_country
3v-workspace/Data_converter pull request #790
Opened 2021-05-18 12:34 UTC by EmmaSamoilova

2021-05-18 13:01 UTC, IegorSoboliev commented on business_register/converter/declaration.py
> +        return country
Consider a case when property_country_data is incorrect

2021-05-19 05:55 UTC, roman-tiukh commented
![image](https://user-images.githubusercontent.com/38906004/118763043-dfcc5600-b87f-11eb-953a-a43d652c2531.png)

2021-05-19 05:58 UTC, roman-tiukh requested changes

2021-05-19 05:58 UTC, roman-tiukh commented on business_register/converter/declaration.py
> +            logger.error(f'Invalid value {property_country_data}')
need to add declaration identification, to known which declaration throw error

2021-05-19 08:31 UTC, roman-tiukh approved these changes

2021-05-19 08:31 UTC, roman-tiukh commented
@IegorSoboliev

2021-05-19 11:36 UTC, IegorSoboliev commented on business_register/converter/declaration.py
> +    def save_property_right(self, property, acquisition_date, rights_data, declaration):
Declaration already is in property)

2021-05-19 11:36 UTC, IegorSoboliev commented on business_register/converter/declaration.py
> +                self.save_property_right(property, acquisition_date, rights_data, declaration)
you can pass here only nacp_declaration_id

2021-05-19 14:48 UTC, roman-tiukh commented on business_register/converter/declaration.py
> +            return city_of_registration
print?

2021-05-19 15:08 UTC, EmmaSamoilova commented on business_register/converter/declaration.py
> +            return city_of_registration
tested and forgot to remove :)

2021-05-21 05:50 UTC, roman-tiukh requested changes

2021-05-21 05:50 UTC, roman-tiukh commented on business_register/converter/declaration.py
> +            #     property_city = self.find_city(property_location, declaration)
wrong comment

2021-05-21 05:50 UTC, roman-tiukh commented on business_register/converter/declaration.py
> +                )
```suggestion
                self.log_error(f'Cannot find country id {property_country_data}')
```

2021-05-21 05:50 UTC, roman-tiukh commented on business_register/converter/declaration.py
> +                self.log_error(f'cannot find declarations of the PEP')
here `self.current_declaration` is have wrong value or None

2021-05-21 05:59 UTC, roman-tiukh requested changes

2021-05-21 05:59 UTC, roman-tiukh commented on business_register/converter/declaration.py
> +                #     self.save_luxuries(detailed_declaration_data['step_5']['data'], declaration)
these changes do not apply to the task

2021-05-21 06:50 UTC, roman-tiukh requested changes
have unresolved comments

2021-05-21 13:53 UTC, roman-tiukh commented
unresolved
![image](https://user-images.githubusercontent.com/38906004/119148285-02639800-ba55-11eb-9849-b116abdbe869.png)

2021-05-24 06:05 UTC, roman-tiukh approved these changes

2021-05-26 07:24 UTC, IegorSoboliev approved these changes

2021-05-26 07:24 UTC, IegorSoboliev commented on business_register/converter/declaration.py
> +        self.log_error(f'Cannot find city')
Consider adding address_data to the error`s message

2021-05-26 10:07 UTC, merged