[DO-1466] Add link to pep.org.ua field
3v-workspace/Data_converter pull request #805
Opened 2021-05-20 16:29 UTC by Iva-khar

2021-05-21 06:47 UTC, roman-tiukh requested changes
no need to add field to model, just add property and calculate url in runtime

2021-05-21 12:21 UTC, Iva-khar commented
> no need to add field to model, just add property and calculate url in runtime

Done. Add to detail, list & short PEP serializers

2021-05-21 13:41 UTC, roman-tiukh requested changes

2021-05-21 13:41 UTC, roman-tiukh commented on business_register/models/pep_models.py
> +    PEP_ORG_UA_PROFILE_URL = 'https://pep.org.ua/uk/person/'
no need this var

2021-05-21 15:11 UTC, Iva-khar commented on business_register/models/pep_models.py
> +    PEP_ORG_UA_PROFILE_URL = 'https://pep.org.ua/uk/person/'
deleted

2021-05-24 05:43 UTC, roman-tiukh approved these changes

2021-05-24 08:01 UTC, IegorSoboliev approved these changes

2021-05-24 08:12 UTC, merged