[DO-1668] Actualize registers updates
3v-workspace/Data_converter pull request #809
Opened 2021-05-24 09:42 UTC by Iva-khar

Add method for actualizing update_at & total_records data in Register model
Add relevant api for KOATUU in fixture

2021-05-25 12:06 UTC, roman-tiukh requested changes
when and who should run this method?

2021-05-26 08:27 UTC, Iva-khar commented
> when and who should run this method?

1. After new project deployement;
2. After someone had run convertors manually or some shanges in registers without downloader.
3. Just now for bring register table up to date
4. Any time for ensure that register table is up to date

2021-05-27 11:41 UTC, Iva-khar commented on data_ocean/fixtures/register.json
> +      "api_detail": "/api/koatuu-fourth-level/{id}/"
Why? We don't have this API at all:x-special/nautilus-clipboard
copy
file:///home/ivan/Pictures/Screenshot%20from%202021-05-27%2014-39-16.png

2021-05-27 12:15 UTC, Iva-khar commented
> how should run this method?

Management command added

2021-05-28 06:10 UTC, roman-tiukh requested changes
I just checkout on your branch and take this error
```
django.core.exceptions.ImproperlyConfigured: Field name `update_at` is not valid for model `Register`.
```
One more
```
TypeError: handle() got an unexpected keyword argument 'verbosity'
```
Koattu register is not clickable at front
![image](https://user-images.githubusercontent.com/38906004/119938098-8c02f080-bf94-11eb-998f-2d022057ba5f.png)

2021-05-28 15:35 UTC, Iva-khar commented
> I just checkout on your branch and take this error
> 
> ```
> django.core.exceptions.ImproperlyConfigured: Field name `update_at` is not valid for model `Register`.
> ```
> 
> One more
> 
> ```
> TypeError: handle() got an unexpected keyword argument 'verbosity'
> ```
> 
> Koattu register is not clickable at front
> ![image](https://user-images.githubusercontent.com/38906004/119938098-8c02f080-bf94-11eb-998f-2d022057ba5f.png)

1. First error - from another PR - it disappiared after rebasing
2. Fixed management command
3. It fixed in front-end PR#135 https://github.com/3v-workspace/DataOcean/pull/135

2021-05-31 06:43 UTC, roman-tiukh commented
![image](https://user-images.githubusercontent.com/38906004/120151197-a3401900-c1f4-11eb-9884-56a694a94b33.png)

2021-05-31 06:43 UTC, roman-tiukh requested changes
![image](https://user-images.githubusercontent.com/38906004/120151248-b7841600-c1f4-11eb-8c11-118bf06207c0.png)
Fixed

2021-06-02 06:08 UTC, roman-tiukh approved these changes

2021-06-02 07:18 UTC, EmmaSamoilova approved these changes

2021-06-02 17:47 UTC, merged