Changed logging to stdout in fetch_peps_nacp_id
3v-workspace/Data_converter pull request #816
Opened 2021-05-26 09:36 UTC by EmmaSamoilova

2021-05-26 11:49 UTC, roman-tiukh requested changes

2021-05-26 11:49 UTC, roman-tiukh commented on business_register/management/commands/fetch_peps_nacp_id.py
>                       f'with NACP id {declaration_id}')
self.stdout.write

2021-05-27 06:45 UTC, IegorSoboliev requested changes

2021-05-27 06:45 UTC, IegorSoboliev commented on business_register/management/commands/fetch_peps_nacp_id.py
better leave that here. We can use this function in another module

2021-05-27 07:20 UTC, roman-tiukh commented on business_register/management/commands/fetch_peps_nacp_id.py
in this case, you need to remove logging from the function and process them outside the function

2021-05-28 08:04 UTC, IegorSoboliev commented on business_register/converter/declaration.py
> +                        except ValueError:
What actually can lead to a ValueError?

2021-05-28 13:25 UTC, EmmaSamoilova commented on business_register/converter/declaration.py
> +                        except ValueError:
DO you mean KeyError is better?

2021-05-31 06:35 UTC, roman-tiukh requested changes

2021-05-31 06:35 UTC, roman-tiukh commented on business_register/converter/declaration.py
> +                        except ValueError:
own error is better

2021-06-01 12:38 UTC, IegorSoboliev approved these changes

2021-06-02 07:42 UTC, roman-tiukh requested changes

2021-06-03 09:16 UTC, roman-tiukh approved these changes

2021-06-03 09:17 UTC, merged