[DO-1886] Add not working converters to report
3v-workspace/Data_converter pull request #820
Opened 2021-05-27 11:19 UTC by Iva-khar

2021-05-27 12:32 UTC, criticus commented on data_ocean/emails.py
> +    not_working = []
please use more explicit name for the variable

2021-05-27 12:35 UTC, criticus commented on data_ocean/models.py
> +    in_daily_report = models.CharField(max_length=20, null=True)
consider renaming to more informative

2021-05-27 13:15 UTC, Iva-khar commented on data_ocean/emails.py
> +    not_working = []
`not_working ` renamed to `not_updated_registers`

2021-05-27 13:16 UTC, Iva-khar commented on data_ocean/models.py
> +    in_daily_report = models.CharField(max_length=20, null=True)
`in_daily_report` renamed to `name_in_daily_report`

2021-05-28 05:40 UTC, roman-tiukh requested changes

2021-05-28 05:40 UTC, roman-tiukh commented on data_ocean/models.py
> +    name_in_daily_report = models.CharField(max_length=20, null=True)
for char fields better user `blank=True default=''`

2021-05-28 16:14 UTC, Iva-khar commented on data_ocean/models.py
> +    name_in_daily_report = models.CharField(max_length=20, null=True)
Done

2021-05-31 06:32 UTC, roman-tiukh requested changes

2021-05-31 06:32 UTC, roman-tiukh commented on data_ocean/emails.py
> +            not_updated_registers.append(register['name_in_daily_report'])
maybe?
```suggestion
    not_updated_registers = Register.objects.exclude(
        name_in_daily_report__in=[report.registry_name for report in reports]
    ).exclude(name_in_daily_report='')
```

2021-06-01 17:53 UTC, Iva-khar commented on data_ocean/emails.py
> +            not_updated_registers.append(register['name_in_daily_report'])
changed

2021-06-02 17:52 UTC, Iva-khar commented on data_ocean/emails.py
> +        to=['ivakhar@gmail.com'],
)

2021-06-02 18:02 UTC, Iva-khar commented on data_ocean/emails.py
> +        to=['ivakhar@gmail.com'],
fixed

2021-06-03 05:35 UTC, roman-tiukh approved these changes

2021-06-03 08:15 UTC, PyDev777 approved these changes

2021-06-03 08:22 UTC, merged