[DO-1892] Transliteration
3v-workspace/Data_converter pull request #824
Opened 2021-05-28 14:32 UTC by Iva-khar

2021-05-28 14:45 UTC, criticus commented on data_ocean/utils.py
> +    'А': 'A',
how is it different from the previous dictionary?

2021-05-31 06:15 UTC, roman-tiukh requested changes
For good result, you should use regexp

2021-05-31 06:15 UTC, roman-tiukh commented on data_ocean/utils.py
> +    return (country + ', ' + transliterate(','.join(string[1:]).lower())).strip()
I think it should be one universal function (except country finding in text). We must write a function for every field in the system?

2021-05-31 06:15 UTC, roman-tiukh commented on data_ocean/utils.py
> +        CompanyType.objects.filter(name=string[0].strip()).first() else transliterate(string[0].strip())
2 requests for DB, we can only one...

2021-05-31 06:15 UTC, roman-tiukh commented on data_ocean/utils.py
> +        Country.objects.filter(name_uk=string[0].strip().lower()).first() else transliterate(string[0].strip())
same(

2021-05-31 06:15 UTC, roman-tiukh commented on data_ocean/utils.py
> +    string = string.strip(' ')
strip()???

2021-05-31 06:15 UTC, roman-tiukh commented on data_ocean/utils.py
> +            return char
:neutral_face: 
```suggestion
    return transliterate_dict.get(char, char)
```

2021-05-31 06:15 UTC, roman-tiukh commented on data_ocean/utils.py
> +    return (company_type + ' ' + transliterate('"' + '"'.join(string[1:]))).strip()
what if address don't have country?

2021-06-01 14:26 UTC, Iva-khar commented on data_ocean/utils.py
> +    return (country + ', ' + transliterate(','.join(string[1:]).lower())).strip()
rewrited

2021-06-01 14:26 UTC, Iva-khar commented on data_ocean/utils.py
> +        CompanyType.objects.filter(name=string[0].strip()).first() else transliterate(string[0].strip())
done

2021-06-01 14:26 UTC, Iva-khar commented on data_ocean/utils.py
> +        Country.objects.filter(name_uk=string[0].strip().lower()).first() else transliterate(string[0].strip())
done

2021-06-01 14:26 UTC, Iva-khar commented on data_ocean/utils.py
> +    string = string.strip(' ')
fixed

2021-06-01 14:26 UTC, Iva-khar commented on data_ocean/utils.py
> +            return char
implemented

2021-06-01 14:27 UTC, Iva-khar commented on data_ocean/utils.py
> +    return (company_type + ' ' + transliterate('"' + '"'.join(string[1:]))).strip()
just transliterate will

2021-06-01 14:28 UTC, Iva-khar commented
Add testing

2021-06-02 07:03 UTC, roman-tiukh reviewed
just use SimpleTestCase

2021-06-02 07:07 UTC, roman-tiukh requested changes

2021-06-02 07:07 UTC, roman-tiukh commented on data_ocean/tests.py
> +        self.assertEqual(transliterate_field(self.testing_company.address, 'address'), address)
completely incorrect test

2021-06-03 14:27 UTC, criticus commented on data_ocean/tests.py
> +        company_ids = list(Company.objects.values('id'))
if we need just one company there is no point to get all and select one, consider using a constant value

2021-06-03 14:42 UTC, criticus commented
what is the reason for writing our own functions instead of using https://pypi.org/project/transliterate/ ?

2021-06-03 16:02 UTC, Iva-khar commented on data_ocean/tests.py
> +        company_ids = list(Company.objects.values('id'))
we gave up the use of db registers in tests

2021-06-03 16:48 UTC, Iva-khar commented
> what is the reason for writing our own functions instead of using https://pypi.org/project/transliterate/ ?

This pack not handle with different transliteration same letters depend of position in word. In ukrainian 5 letters with different transliteration depends of it's first position in word or others

2021-06-03 18:38 UTC, criticus commented
> > what is the reason for writing our own functions instead of using https://pypi.org/project/transliterate/ ?
> 
> This pack not handle with different transliteration same letters depend of position in word. In ukrainian 5 letters with different transliteration depends of it's first position in word or others

I believe you can use `pre_processor_mapping` to replace characters at the beginning of words

2021-06-03 20:16 UTC, criticus commented
for example, see https://github.com/barseghyanartur/transliterate/issues/52

2021-06-04 06:37 UTC, roman-tiukh commented
@criticus I will check this

2021-06-07 09:45 UTC, Iva-khar commented on data_ocean/utils.py
> +ukr_to_en_first_word = {
done

2021-06-07 09:46 UTC, Iva-khar commented on data_ocean/utils.py
> +    'А': 'A',
fist dictionary for the first letter in the word, second dictionary for oters words

2021-06-07 09:48 UTC, Iva-khar commented on data_ocean/tests.py
> +        self.assertEqual(transliterate_field(self.testing_company.address, 'address'), address)
rewritted

2021-06-07 11:08 UTC, roman-tiukh requested changes

2021-06-07 11:08 UTC, roman-tiukh commented on data_ocean/tests.py
> +        )
more pretty and readable
![image](https://user-images.githubusercontent.com/38906004/121006622-c1c88600-c799-11eb-8f4a-d2f92a96f92e.png)

2021-06-07 11:12 UTC, Iva-khar commented on data_converter/settings_local.base.py
> +TEST_RUNNER = 'data_ocean.tests.NoDbTestRunner'
done

2021-06-07 11:13 UTC, Iva-khar commented on data_ocean/transliteration/constants.py
> +    '’': '',
done

2021-06-07 11:15 UTC, Iva-khar commented on data_ocean/transliteration/constants.py
> +    '’': '',
I can't delete '

2021-06-07 11:44 UTC, Iva-khar commented on data_ocean/tests.py
> +        )
done

2021-06-08 08:34 UTC, roman-tiukh approved these changes

2021-06-08 10:05 UTC, PyDev777 approved these changes

2021-06-08 10:06 UTC, merged