[DO-1826] Download fields relationship_type and relationship_type_en from pep.org.ua
3v-workspace/Data_converter pull request #825
Opened 2021-05-29 18:14 UTC by Andrii17s

2021-05-31 06:29 UTC, roman-tiukh requested changes

2021-05-31 06:29 UTC, roman-tiukh commented on business_register/models/pep_models.py
> +    relationship_type_en = models.CharField(_("connection`s type in English"), max_length=550, null=True,
localization?

2021-05-31 07:10 UTC, roman-tiukh reviewed
I confirm the PR but I will merge it a little later

2021-05-31 07:11 UTC, roman-tiukh commented
we are waiting for second approve

2021-05-31 12:08 UTC, IegorSoboliev requested changes

2021-05-31 12:08 UTC, IegorSoboliev commented on business_register/converter/pep.py
> +                        update_fields.append('relationship_type')
in all cases you should update also 'updated_at' field

2021-05-31 12:26 UTC, roman-tiukh commented on business_register/converter/pep.py
> +                        update_fields.append('relationship_type')
?

2021-05-31 12:39 UTC, Andrii17s commented on business_register/converter/pep.py
> +                        update_fields.append('relationship_type')
`
if update_fields:                        update_fields.append('updated_at')                        already_stored_link.save(update_fields=update_fields)                        is_changed = True
`
Line 576

2021-05-31 13:31 UTC, EmmaSamoilova approved these changes

2021-05-31 14:11 UTC, IegorSoboliev approved these changes

2021-06-01 12:41 UTC, IegorSoboliev commented on business_register/converter/pep.py
> +                        update_fields.append('relationship_type')
! Yes, pardon. Forgot my own code)))

2021-06-03 09:18 UTC, roman-tiukh approved these changes

2021-06-03 09:18 UTC, merged