[1805] Download all fullname_en from pep.org.ua
3v-workspace/Data_converter pull request #837
Opened 2021-06-01 11:19 UTC by Andrii17s

Create new field fullname_en and download data in it.

2021-06-01 12:39 UTC, IegorSoboliev approved these changes

2021-06-01 13:01 UTC, roman-tiukh requested changes

2021-06-01 13:01 UTC, roman-tiukh commented on business_register/converter/pep.py
> +            fullname_en = pep_dict['last_name_en'].lower() + ' ' + pep_dict['first_name_en'].lower() + ' ' + \
create pls first_name_en middle_name_en last_name_en variables and use they below

2021-06-02 05:48 UTC, roman-tiukh requested changes
this is PepConverterFromJson........

2021-06-03 09:15 UTC, roman-tiukh approved these changes

2021-06-03 09:16 UTC, merged