[1806] Display filled fields in API
3v-workspace/Data_converter pull request #838
Opened 2021-06-01 11:21 UTC by Andrii17s

company.name_en 
pep.fullname_en

2021-06-01 12:38 UTC, IegorSoboliev approved these changes

2021-06-02 05:37 UTC, EmmaSamoilova approved these changes

2021-06-02 05:43 UTC, roman-tiukh requested changes
these are not all serializers to which you need to add

2021-06-03 10:44 UTC, roman-tiukh approved these changes

2021-06-03 10:44 UTC, merged