[DO-1777] check Storing property and Storing luxuries from Declaration
3v-workspace/Data_converter pull request #842
Opened 2021-06-02 09:00 UTC by EmmaSamoilova

2021-06-02 13:57 UTC, roman-tiukh approved these changes

2021-06-03 12:36 UTC, Iva-khar approved these changes

2021-06-03 12:36 UTC, Iva-khar commented on business_register/converter/declaration.py
> +                        spouse = Pep.objects.filter(nacp_id=nacp_id).first()
```suggestion
                    if isinstance(nacp_id, int):
                        spouse = Pep.objects.filter(nacp_id=nacp_id).first()
                    else:
                        self.log_error(f'Invalid value: nacp_id = {nacp_id}')
```

2021-06-03 12:36 UTC, Iva-khar commented on business_register/converter/declaration.py
> +                        spouse = Pep.objects.filter(nacp_id=nacp_id).first()
Maybe...

2021-06-03 12:36 UTC, Iva-khar commented on business_register/converter/declaration.py
> +                break
What if `relative_data` is `int `or `float` for example?

2021-06-03 12:46 UTC, EmmaSamoilova commented on business_register/converter/declaration.py
> +                        spouse = Pep.objects.filter(nacp_id=nacp_id).first()
I saw the wrong id value only nacp_id = 'declarationType' and in some declaration nacp_id = 0

2021-06-03 12:46 UTC, EmmaSamoilova commented on business_register/converter/declaration.py
> +                break
I have not seen int and float values

2021-06-03 13:28 UTC, Iva-khar commented on business_register/converter/declaration.py
> +                break
Must check that type what kind you are waiting for. The same in previous comment.

2021-06-03 13:29 UTC, Iva-khar commented on business_register/converter/declaration.py
> +                        spouse = Pep.objects.filter(nacp_id=nacp_id).first()
When will appear new wrong type you will rewrite it?

2021-06-03 13:33 UTC, Iva-khar requested changes

2021-06-03 13:33 UTC, Iva-khar commented on business_register/converter/declaration.py
> +            'Не визначено'
It seems strange. So different formatting...

2021-06-03 13:37 UTC, Iva-khar commented on business_register/converter/declaration.py
> +                        spouse = Pep.objects.filter(nacp_id=nacp_id).first()
& `nacp_id = 'declarationType' ` it's string, not object of declaration isn't it?

2021-06-03 20:24 UTC, criticus commented on business_register/models/declaration_models.py
> +    valuation = models.FloatField(
float or decimal?

2021-06-04 05:30 UTC, roman-tiukh commented on business_register/converter/declaration.py
> +                break
@Iva-khar +++

2021-06-04 05:31 UTC, roman-tiukh commented on business_register/models/declaration_models.py
> +    valuation = models.FloatField(
if this is money then should be decimal

2021-06-04 05:32 UTC, roman-tiukh commented on business_register/converter/declaration.py
> +                        spouse = Pep.objects.filter(nacp_id=nacp_id).first()
@Iva-khar +

2021-06-04 09:30 UTC, roman-tiukh approved these changes

2021-06-04 13:21 UTC, Iva-khar approved these changes

2021-06-04 13:24 UTC, EmmaSamoilova commented on business_register/converter/declaration.py
> +                        spouse = Pep.objects.filter(nacp_id=nacp_id).first()
fixed

2021-06-04 13:24 UTC, EmmaSamoilova commented on business_register/converter/declaration.py
> +                break
fixed

2021-06-04 13:25 UTC, EmmaSamoilova commented on business_register/models/declaration_models.py
> +    valuation = models.FloatField(
done

2021-06-07 06:23 UTC, merged