[DO-1808] Add english translations sections kved
3v-workspace/Data_converter pull request #860
Opened 2021-06-08 12:21 UTC by Iva-khar

For filling eng kved run `$python manage.py fill_eng_kved_sections`
Or run `KvedConverter().save_to_db()` if KVED DB is empty

2021-06-09 08:55 UTC, roman-tiukh requested changes

2021-06-09 08:55 UTC, roman-tiukh commented on business_register/models/pep_models.py
> -
???

2021-06-09 08:55 UTC, roman-tiukh commented on business_register/models/company_models.py
> -
???

2021-06-09 08:55 UTC, roman-tiukh commented on business_register/converter/kved.py
> +            section.save()
add update_fields to save method

2021-06-09 12:41 UTC, Iva-khar commented on business_register/models/pep_models.py
> -
fixed

2021-06-09 12:41 UTC, Iva-khar commented on business_register/models/company_models.py
> -
fixed

2021-06-09 12:41 UTC, Iva-khar commented on business_register/converter/kved.py
> +            section.save()
done

2021-06-10 08:43 UTC, roman-tiukh requested changes
need to add new field to kved serializator

2021-06-11 12:32 UTC, Iva-khar commented
> need to add new field to kved serializator

Added properties to `CompanyToKved` model for use in new `CompanyToKvedSerializer`
Kveds in Company API represents like:
```
"kveds": [
                {
                    "code": "41.10",
                    "name": "організація будівництва будівель",
                    "group": "організація будівництва будівель",
                    "division": "будівництво будівель",
                    "section": "будівництво",
                    "section_en": "construction",
                    "primary_kved": false
                },
                {
                    "code": "20.41",
                    "name": "виробництво мила та мийних засобів, засобів для чищення та полірування",
                    "group": "виробництво мила та мийних засобів, засобів для чищення та полірування, парфумних і косметичних засобів",
                    "division": "виробництво хімічних речовин і хімічної продукції",
                    "section": "переробна промисловість",
                    "section_en": "manufacturing",
                    "primary_kved": false
                }
]
```

2021-06-14 05:57 UTC, roman-tiukh requested changes

2021-06-14 05:57 UTC, roman-tiukh commented on business_register/models/company_models.py
> +        if self.kved:
is kved can be None??

2021-06-14 05:57 UTC, roman-tiukh commented on business_register/models/company_models.py
> +            return None
move this to serializer
like:
```
section_en = serializers.CharField(source="kved.section.name_en")
```
`select_related` will be good

2021-06-14 09:18 UTC, Iva-khar commented on business_register/models/company_models.py
> +            return None
+

2021-06-14 11:20 UTC, Iva-khar commented on business_register/models/company_models.py
> +        if self.kved:
rewrited

2021-06-14 11:20 UTC, Iva-khar commented on business_register/models/company_models.py
> +            return None
done

2021-06-15 07:43 UTC, roman-tiukh approved these changes

2021-06-15 08:09 UTC, EmmaSamoilova approved these changes

2021-06-15 08:46 UTC, merged