DO-1844 Store unfinished construction
3v-workspace/Data_converter pull request #862
Opened 2021-06-08 18:10 UTC by OlexandrTopuzov

2021-06-08 18:12 UTC, OlexandrTopuzov reviewed
@roman-tiukh 
@EmmaSamoilova

2021-06-09 08:51 UTC, roman-tiukh requested changes

2021-06-09 08:51 UTC, roman-tiukh commented on business_register/models/declaration_models.py
> +    )
why we need this fied?

2021-06-09 09:15 UTC, OlexandrTopuzov commented on business_register/models/declaration_models.py
> +    )
so said to do Єhor, I suppose that the structures in the subsequent can beat the completion

2021-06-09 09:59 UTC, roman-tiukh commented on business_register/models/declaration_models.py
> +    )
BooleandField should have default value and dont have null=True

2021-06-09 10:55 UTC, OlexandrTopuzov commented on business_register/models/declaration_models.py
> +    )
the fact is that we need to apply this field only to type 6 and if the default is true, then all types will be true

2021-06-10 08:49 UTC, roman-tiukh commented
wait for Iegor`s review

2021-06-10 12:06 UTC, roman-tiukh approved these changes

2021-06-10 12:06 UTC, merged

2021-06-10 12:40 UTC, EmmaSamoilova commented on business_register/converter/declaration.py
> +            country = self.find_country(data['country'])
There may be a KeyError if the 'country' key is missing. Or is 'country' in all declarations?

2021-06-10 12:42 UTC, EmmaSamoilova commented on business_register/converter/declaration.py
> +            country = self.find_country(data['country'])
There may be a KeyError if the 'country' key is missing. Or is 'country' in all declarations?