[1804] Fill up all name_en fields on pep related companies
3v-workspace/Data_converter pull request #866
Opened 2021-06-09 13:27 UTC by Andrii17s

2021-06-09 14:28 UTC, criticus approved these changes

2021-06-10 06:55 UTC, roman-tiukh requested changes

2021-06-10 06:55 UTC, roman-tiukh commented on business_register/converter/pep.py
> +                    company_name_en = transliterate(company_name)
first what you need: pass comany_name to `translate_company_type_in_string`

2021-06-10 06:55 UTC, roman-tiukh commented on business_register/converter/pep.py
> +                if company_name_en is None:
`company_name_en` can be empty string for example

2021-06-10 06:55 UTC, roman-tiukh commented on business_register/converter/pep.py
> +                    company_update_fields.append('name_en')
same

2021-06-10 06:55 UTC, roman-tiukh commented on business_register/converter/pep.py
> +    translate_country_in_string
unused imports

2021-06-11 07:17 UTC, roman-tiukh commented on business_register/converter/pep.py
> +                if company_name_en is None and company_name:
what if company company_name_en is empty string?
```suggestion
                if not company_name_en:
```

2021-06-11 07:49 UTC, Iva-khar approved these changes

2021-06-14 08:47 UTC, roman-tiukh requested changes

2021-06-14 08:47 UTC, roman-tiukh commented on business_register/converter/pep.py
> +                if not company.name_en and company_name:
here?

2021-06-16 10:37 UTC, roman-tiukh commented on business_register/converter/pep.py
> +                company_update_fields.append('name_en')
why?
`company_update_fields.append('name_en')`

2021-06-16 10:42 UTC, roman-tiukh approved these changes

2021-06-16 10:42 UTC, merged