DO-1850 Store unfinished construction rights
3v-workspace/Data_converter pull request #873
Opened 2021-06-11 10:19 UTC by OlexandrTopuzov

2021-06-14 05:40 UTC, roman-tiukh requested changes

2021-06-14 05:40 UTC, roman-tiukh commented on business_register/converter/declaration.py
> +                full_name = ''
first_name and last_name is required

2021-06-14 05:40 UTC, roman-tiukh commented on business_register/converter/declaration.py
> +                full_name=full_name,
do we store first, last, middle names separately? I think we should do this

2021-06-14 05:40 UTC, roman-tiukh commented on business_register/converter/declaration.py
> +                pep = Pep.objects.filter(nacp_id=int(other_owner_info)).first()
wait for Emma`s PR. nacp_id will be a array of ids

2021-06-18 05:13 UTC, EmmaSamoilova commented on business_register/converter/declaration.py
> +                pep = Pep.objects.filter(nacp_id=int(owner_info)).first()
pep = self.find_person(owner_info)

2021-06-18 05:14 UTC, EmmaSamoilova commented on business_register/converter/declaration.py
> +                pep = Pep.objects.filter(nacp_id=int(other_owner_info)).first()
pep = self.find_person(other_owner_info)

2021-06-24 11:05 UTC, closed without merging