[DO-1974] Fix saving nacp id of related persons
3v-workspace/Data_converter pull request #874
Opened 2021-06-11 12:00 UTC by EmmaSamoilova

2021-06-14 05:33 UTC, roman-tiukh requested changes

2021-06-14 05:33 UTC, roman-tiukh commented on business_register/converter/declaration.py
> +                    continue
you can catch this error only in is_same_full_name

2021-06-14 05:33 UTC, roman-tiukh commented on business_register/management/commands/fetch_peps_nacp_id.py
> +            nacp_id=[]
__len=0?

2021-06-14 05:33 UTC, roman-tiukh commented on business_register/migrations/0118_auto_20210611_0951.py
> +        ),
you can save all id:
1. add array-field `nacp_id1`
2. move id data from `nacp_id` to `nacp_id1`
3. remove field `nacp_id`
4. rename field `nacp_id1` to `nacp_id`

2021-06-14 05:33 UTC, roman-tiukh commented on business_register/converter/declaration.py
> +        return pep
```suggestion
    def find_person(self, pep_id):
        peps = list(Pep.objects.filter(nacp_id__contains=[int(pep_id)]))
        if len(peps) == 1:
            return peps[0]
        elif len(peps) > 1:
            self.log_error(f'More than one person has nacp_id = {pep_id}')
        return None
```

2021-06-14 05:33 UTC, roman-tiukh commented on business_register/converter/declaration.py
> +            )
```suggestion
            related_person_links = RelatedPersonsLink.objects.filter(
                from_person=pep,
                to_person_relationship_type=to_person_relationship_type
            )
```

2021-06-14 05:33 UTC, roman-tiukh commented on business_register/management/commands/fetch_peps_nacp_id.py
> +            and pep.middle_name.capitalize() == middle_name.capitalize().strip()
```suggestion
            pep.last_name.lower() == last_name.lower().strip()
            and pep.first_name.lower() == first_name.lower().strip()
            and pep.middle_name.lower() == middle_name.lower().strip()
```

2021-06-14 11:28 UTC, EmmaSamoilova commented on business_register/converter/declaration.py
> +                    continue
done

2021-06-14 11:28 UTC, EmmaSamoilova commented on business_register/management/commands/fetch_peps_nacp_id.py
> +            nacp_id=[]
done

2021-06-14 11:28 UTC, EmmaSamoilova commented on business_register/converter/declaration.py
> +        return pep
done

2021-06-14 11:28 UTC, EmmaSamoilova commented on business_register/management/commands/fetch_peps_nacp_id.py
> +            and pep.middle_name.capitalize() == middle_name.capitalize().strip()
done

2021-06-14 11:31 UTC, EmmaSamoilova commented on business_register/migrations/0118_auto_20210611_0951.py
> +        ),
done, but I'm not sure about the SQL query

2021-06-14 13:53 UTC, EmmaSamoilova commented on business_register/converter/declaration.py
> +            )
done

2021-06-15 07:04 UTC, roman-tiukh requested changes

2021-06-15 07:04 UTC, roman-tiukh commented on business_register/migrations/0118_auto_20210614_0723.py
> +                WHERE nacp_id IS NOT NULL;
is this sql works??

2021-06-15 10:25 UTC, EmmaSamoilova commented on business_register/migrations/0118_auto_20210614_0723.py
> +        ),
'historicalpep' and 'pep'

2021-06-15 10:25 UTC, EmmaSamoilova commented on business_register/migrations/0118_auto_20210614_0723.py
> +        )
'historicalpep' and 'pep'

2021-06-15 10:25 UTC, EmmaSamoilova commented on business_register/migrations/0118_auto_20210614_0723.py
> +                WHERE nacp_id IS NOT NULL;
fix

2021-06-15 12:17 UTC, closed without merging