[DO - 1720]
3v-workspace/Data_converter pull request #908
Opened 2021-06-24 14:32 UTC by Andrii17s

0)Create BaseScoringRule class
1)Create PEP03 scoring rule

2021-06-24 14:48 UTC, IegorSoboliev requested changes

2021-06-24 14:48 UTC, IegorSoboliev commented on business_register/pep_scoring/rules.py
> +            created_at__year__gte=2015,
created_at is the time of storing the record in our DB. We should use PropertyRight.acquisition date field for this check

2021-06-24 14:48 UTC, IegorSoboliev commented on business_register/pep_scoring/rules.py
> +            created_at__year__gte=2015,
same here

2021-06-24 14:48 UTC, IegorSoboliev commented on business_register/pep_scoring/rules.py
> +            created_at__year__gte=2015,
and here

2021-06-24 14:48 UTC, IegorSoboliev commented on business_register/pep_scoring/rules.py
> +            created_at__year__gte=2015,
VehicleRight. acquisition_date

2021-06-24 14:48 UTC, IegorSoboliev commented on business_register/pep_scoring/rules.py
> +            created_at__year__gte=2015,
VehicleRight. acquisition_date

2021-06-25 05:31 UTC, roman-tiukh commented on business_register/pep_scoring/rules.py
> +                "weight": 0.4,
weight should be saved at another field not in json

2021-06-25 05:31 UTC, roman-tiukh commented on business_register/pep_scoring/rules.py
> +        ).values_list('id', flat=True).all()[::1]
values_list('id', flat=True) already return list
```suggestion
        family_ids = self.pep.related_persons.filter(
            to_person_links__category=RelatedPersonsLink.FAMILY,
        ).values_list('id', flat=True)
```

2021-06-25 09:26 UTC, IegorSoboliev approved these changes

2021-06-25 09:47 UTC, roman-tiukh commented on business_register/pep_scoring/rules.py
> +        return 0
1. no need to call `json.dumps`
2. function should return same result if don't `have_weight` 
like this ->
```suggestion
            return weight, data
        return 0, {}
```

2021-06-25 10:28 UTC, roman-tiukh approved these changes

2021-06-25 10:28 UTC, merged