Refactor save vehicle
3v-workspace/Data_converter pull request #909
Opened 2021-06-24 18:45 UTC by OlexandrTopuzov

2021-06-25 14:53 UTC, EmmaSamoilova approved these changes

2021-06-28 08:12 UTC, roman-tiukh requested changes

2021-06-28 08:12 UTC, roman-tiukh commented on business_register/models/declaration_models.py
> +    AGRICULTURAL_MACHINERY = 6
don`t change numbers for options, allowed only adding new numbers

2021-06-28 09:02 UTC, OlexandrTopuzov commented on business_register/models/declaration_models.py
> +    AGRICULTURAL_MACHINERY = 6
done

2021-06-28 10:30 UTC, roman-tiukh approved these changes

2021-06-29 06:02 UTC, merged