[DO-1906] Add_ukrainian_language_search_country_of_registration
3v-workspace/Data_converter pull request #912
Opened 2021-06-25 13:18 UTC by Iva-khar

Added `country_of_registration_uk` filter

2021-06-28 06:02 UTC, EmmaSamoilova approved these changes

2021-06-28 07:46 UTC, roman-tiukh requested changes

2021-06-28 07:46 UTC, roman-tiukh commented on business_register/filters.py
>      )
We talked about the fact that it should be one filter for both fields at once

2021-06-28 17:55 UTC, Iva-khar commented on business_register/filters.py
>      )
done

2021-06-29 05:36 UTC, roman-tiukh requested changes

2021-06-29 05:36 UTC, roman-tiukh commented on business_register/views/sanction_views.py
> +        'country_of_registration__name_uk',
here

2021-06-29 05:36 UTC, roman-tiukh commented on business_register/filters.py
> +
Meta should located at bottom of FilterSet

2021-06-29 05:38 UTC, roman-tiukh requested changes

2021-06-29 05:38 UTC, roman-tiukh commented on business_register/filters.py
> +        method='filter_en_and_uk_fields',
method needs to be named clearer

2021-06-29 08:59 UTC, Iva-khar commented on business_register/views/sanction_views.py
> +        'country_of_registration__name_uk',
?
delete it?

2021-06-29 08:59 UTC, Iva-khar commented on business_register/filters.py
> +
done

2021-06-29 09:26 UTC, Iva-khar commented on business_register/filters.py
> +        method='filter_en_and_uk_fields',
done

2021-06-30 06:02 UTC, roman-tiukh approved these changes

2021-06-30 06:02 UTC, merged