[DO - 1730] Create PEP11 scoring rule
3v-workspace/Data_converter pull request #914
Opened 2021-06-27 13:06 UTC by Andrii17s

Royalty exceeds 20% of the total income indicated in the declaration.

2021-06-28 08:03 UTC, roman-tiukh commented on business_register/pep_scoring/rules.py
> +                declaration_ids[declaration['year']] = list()
```suggestion
            if year not in declaration_ids:
                declaration_ids[declaration['year']] = []
```

2021-06-28 11:22 UTC, roman-tiukh approved these changes

2021-07-05 13:06 UTC, Andrii17s commented on business_register/pep_scoring/rules.py
> +        incomes = Income.objects.filter(
But we need all other Income types to calculate how much is 20%

2021-07-06 16:42 UTC, IegorSoboliev approved these changes

2021-07-06 18:23 UTC, criticus commented on business_register/pep_scoring/rules.py
> +class IsMuchRoyalty(BaseScoringRule):
class name has to be noun

2021-07-07 08:23 UTC, IegorSoboliev approved these changes

2021-07-07 09:47 UTC, roman-tiukh requested changes

2021-07-07 09:47 UTC, roman-tiukh commented on business_register/pep_scoring/rules.py
> +            except:
except all errors its bad practice

2021-07-07 10:56 UTC, roman-tiukh approved these changes

2021-07-07 10:56 UTC, merged