[DO-1732] Create PEP15 scoring rule
3v-workspace/Data_converter pull request #915
Opened 2021-06-27 13:26 UTC by Andrii17s

Rule 15
Declared presents amounting to more than 100 000 UAH

2021-06-28 08:08 UTC, roman-tiukh commented on business_register/pep_scoring/rules.py
> +            if not declaration_ids.__contains__(year):
```suggestion
            if year not in declaration_ids:
```

2021-06-28 08:08 UTC, roman-tiukh commented on business_register/pep_scoring/rules.py
> +                declaration_ids[declaration['year']] = list()
```suggestion
                declaration_ids[declaration['year']] = []
```

2021-06-28 11:21 UTC, roman-tiukh approved these changes

2021-07-06 07:23 UTC, IegorSoboliev approved these changes

2021-07-06 07:28 UTC, roman-tiukh approved these changes

2021-07-06 09:02 UTC, roman-tiukh requested changes

2021-07-06 09:02 UTC, roman-tiukh commented on business_register/pep_scoring/rules.py
> +
@register_rule

2021-07-06 09:04 UTC, roman-tiukh approved these changes

2021-07-06 09:04 UTC, merged