[DO-1750] Create PEP18 scoring rule
3v-workspace/Data_converter pull request #918
Opened 2021-06-27 14:31 UTC by Andrii17s

Rule 18
Declared ownership and/or right of use of a business class car, or car with a price exceeding 800 000 UAH or brand vehicle, which is considered to be a luxury car

2021-06-28 07:57 UTC, roman-tiukh requested changes

2021-06-28 07:57 UTC, roman-tiukh commented on business_register/pep_scoring/rules.py
> +        print(have_car)
remove prints

2021-06-28 07:57 UTC, roman-tiukh commented on business_register/pep_scoring/rules.py
> +            valuation__gt=max_price,
```suggestion
            valuation__gte=max_price,
```

2021-06-28 07:57 UTC, roman-tiukh commented on business_register/pep_scoring/rules.py
> +            is_luxury=True
how do we calculate luxury?

2021-06-28 11:25 UTC, Andrii17s commented on business_register/pep_scoring/rules.py
> +            is_luxury=True
It based on pep.org.ua data, until we haven't our method yet.

2021-07-12 16:18 UTC, criticus commented
@EmmaSamoilova should this one be closed?

2021-07-12 16:45 UTC, EmmaSamoilova commented
> @EmmaSamoilova should this one be closed?

maybe yes, I think I've finished this rule.

2021-07-16 09:15 UTC, closed without merging