[DO-1752] Create PEP19 scoring rule
3v-workspace/Data_converter pull request #919
Opened 2021-06-27 14:36 UTC by Andrii17s

Rule 19
Declared ownership and/or right of use of more than 5 cars

2021-06-28 07:53 UTC, roman-tiukh requested changes

2021-06-28 07:53 UTC, roman-tiukh commented on business_register/pep_scoring/rules.py
> +        return 0
```suggestion
        return 0, {}
```

2021-06-28 07:53 UTC, roman-tiukh commented on business_register/pep_scoring/rules.py
> +                    "count": total,
```suggestion
                    "total_cars_have": total,
```

2021-06-29 05:56 UTC, roman-tiukh approved these changes

2021-07-07 12:53 UTC, IegorSoboliev commented on business_register/pep_scoring/rules.py
> +        owner_types = [VehicleRight.OWNERSHIP, VehicleRight.BENEFICIAL_OWNERSHIP, VehicleRight.JOINT_OWNERSHIP,
I think here we can sum all cars. Please, verify this with Nastya

2021-07-07 12:53 UTC, IegorSoboliev commented on business_register/pep_scoring/rules.py
> +        have_rights = VehicleRight.objects.filter(
Do we have several rights on the same car?

2021-07-07 12:53 UTC, IegorSoboliev commented on business_register/pep_scoring/rules.py
> +            acquisition_date__year=year,
What is the reason to use acquisition_date__year? My car is 4-years old, and it should be counted

2021-07-07 12:53 UTC, IegorSoboliev commented on business_register/pep_scoring/rules.py
> +        total_cars_have = serializers.IntegerField(min_value=0, required=True)
There are different types of Vehicle. I think we need only cars. Please, verify this with Nastya

2021-07-08 10:01 UTC, closed without merging