[DO-1755] Create PEP21 scoring rule
3v-workspace/Data_converter pull request #920
Opened 2021-06-27 14:56 UTC by Andrii17s

Rule 21
Monetary assets declared this year exceed the sum of income and amount of monetary assets of the previous year

2021-06-28 07:51 UTC, roman-tiukh reviewed
Do we have good logic for work with currencies?
I find 16 currencies for example:
```
    'UAH',
    'USD',
    'EUR',
    'RUB',
    'CHF',
    'GBP',
    'PLN',
    'CAD',
    'GEL',
    'CNY',
    'HRK',
    'SEK',
    'AUD',
    'TRY',
    'JPY',
    'HUF',
    'CZK',
```

2021-06-28 07:51 UTC, roman-tiukh requested changes
blocked for now

2021-06-29 14:49 UTC, IegorSoboliev commented on business_register/pep_scoring/rules.py
> +        declarations = Declaration.objects.filter(
I think we have to use only the last two declarations for this rule

2021-07-04 17:58 UTC, Andrii17s commented on business_register/pep_scoring/rules.py
> +        declarations = Declaration.objects.filter(
@IegorSoboliev Why two, not just the last one?

2021-07-08 14:36 UTC, closed without merging