[DO-2055] Added method for find third person
3v-workspace/Data_converter pull request #924
Opened 2021-06-28 10:12 UTC by EmmaSamoilova

2021-06-29 09:22 UTC, IegorSoboliev requested changes

2021-06-29 09:22 UTC, IegorSoboliev commented on business_register/converter/declaration.py
> +        OTHER_PERSON_TYPES = {
Consider initializing that in the __init__() method of the DeclarationConverter class. Then we can use it in all other classes

2021-06-29 09:22 UTC, IegorSoboliev commented on business_register/converter/declaration.py
> +            full_name = right_data.get('ua_company_name')
Only a person can have the full name). Maybe, company name?

2021-06-29 13:06 UTC, EmmaSamoilova commented on business_register/converter/declaration.py
> +        OTHER_PERSON_TYPES = {
done

2021-06-29 13:06 UTC, EmmaSamoilova commented on business_register/converter/declaration.py
> +            full_name = right_data.get('ua_company_name')
done

2021-06-29 14:09 UTC, IegorSoboliev approved these changes

2021-06-29 16:32 UTC, OlexandrTopuzov approved these changes

2021-06-30 07:20 UTC, roman-tiukh approved these changes

2021-06-30 07:23 UTC, merged