[DO-2077] Export pep view
3v-workspace/Data_converter pull request #946
Opened 2021-07-01 22:45 UTC by Iva-khar

2021-07-02 04:37 UTC, roman-tiukh commented on business_register/views/pep_views.py
> +        }
needs localization

2021-07-02 04:37 UTC, roman-tiukh commented on business_register/forms.py
>      days_limit = settings.PEP_EXPORT_XLSX_DAYS_LIMIT
in this case we don't need PeriodLimitationForm

2021-07-13 15:38 UTC, Iva-khar commented on business_register/views/pep_views.py
> +        }
done

2021-07-15 14:43 UTC, roman-tiukh approved these changes

2021-07-16 06:13 UTC, IegorSoboliev commented on business_register/models/fop_models.py
> +    authority = models.ForeignKey(Authority, related_name='authority', on_delete=models.CASCADE,
maybe, 'registered_fops'?

2021-07-16 06:20 UTC, roman-tiukh approved these changes

2021-07-16 06:20 UTC, roman-tiukh commented on business_register/models/fop_models.py
> +    authority = models.ForeignKey(Authority, related_name='authority', on_delete=models.CASCADE,
```suggestion
    authority = models.ForeignKey(Authority, related_name='registered_fops', on_delete=models.CASCADE,
```

2021-07-16 06:20 UTC, roman-tiukh commented on business_register/views/fop_views.py
> +from django.utils.translation import gettext_lazy as _, gettext as __
wrong imports...

2021-07-16 06:20 UTC, roman-tiukh commented on business_register/views/pep_views.py
> +from django.utils.translation import gettext_lazy as _, gettext as __
wrong import...

2021-07-16 06:20 UTC, roman-tiukh commented on data_ocean/export.py
> +        serializer = import_string(serializer_module)(queryset, many=True)
wait... why do we import all this?

2021-07-16 06:21 UTC, roman-tiukh requested changes
blocked

2021-07-16 15:36 UTC, Iva-khar commented on business_register/views/fop_views.py
> +from django.utils.translation import gettext_lazy as _, gettext as __
rewrited

2021-07-16 15:37 UTC, Iva-khar commented on business_register/views/pep_views.py
> +from django.utils.translation import gettext_lazy as _, gettext as __
rewrited

2021-07-16 15:37 UTC, Iva-khar commented on data_ocean/export.py
> +        serializer = import_string(serializer_module)(queryset, many=True)
selery not receive objects

2021-07-16 18:04 UTC, Iva-khar commented on business_register/models/fop_models.py
> +    authority = models.ForeignKey(Authority, related_name='authority', on_delete=models.CASCADE,
just deleted

2021-07-22 13:11 UTC, roman-tiukh approved these changes

2021-07-22 15:07 UTC, merged