[DO-1906] Filter_two_fields_sitizenship_country
3v-workspace/Data_converter pull request #951
Opened 2021-07-02 15:18 UTC by Iva-khar

2021-07-05 05:23 UTC, roman-tiukh approved these changes

2021-07-05 05:24 UTC, roman-tiukh requested changes

2021-07-05 05:24 UTC, roman-tiukh commented on business_register/filters.py
> +    countries_of_citizenship = filters.CharFilter(
```suggestion
    country_of_citizenship = filters.CharFilter(
```

2021-07-13 09:36 UTC, PyDev777 approved these changes

2021-07-13 16:52 UTC, roman-tiukh approved these changes

2021-07-13 16:52 UTC, merged