[DO - 1720] Create PEP03 scoring rule
3v-workspace/Data_converter pull request #959
Opened 2021-07-04 15:27 UTC by Andrii17s

2021-07-05 14:29 UTC, IegorSoboliev requested changes

2021-07-05 14:29 UTC, IegorSoboliev commented on business_register/pep_scoring/rules.py
> +            property__declaration__year=self.declaration.year,
Please, explain why type is only Property.SUMMER_HOUSE?! We do have:     
    ```
    HOUSE = 1
    SUMMER_HOUSE = 2
    APARTMENT = 3
    ROOM = 4
    GARAGE = 5
    UNFINISHED_CONSTRUCTION = 6
    OFFICE = 8
    OTHER = 10

```

2021-07-05 14:29 UTC, IegorSoboliev commented on business_register/pep_scoring/rules.py
> +            property__declaration__year=self.declaration.year,
We have no need to filter year. You can get all data from the declaration that we check

2021-07-05 14:32 UTC, Andrii17s commented on business_register/pep_scoring/rules.py
> +            property__declaration__year=self.declaration.year,
We also check family members declarations, and should filter it by the year.

2021-07-05 14:34 UTC, Andrii17s commented on business_register/pep_scoring/rules.py
> +            property__declaration__year=self.declaration.year,
"Real estate is property consisting of land and the buildings on it", nothing else except SUMMER_HOUSE didn't look suitable for me

2021-07-05 14:38 UTC, IegorSoboliev commented on business_register/pep_scoring/rules.py
> +            property__declaration__year=self.declaration.year,
Family members property should always be in PEP`s declaration

2021-07-05 14:40 UTC, IegorSoboliev commented on business_register/pep_scoring/rules.py
> +            property__declaration__year=self.declaration.year,
As far as I understand al these types should be included in the rule

2021-07-05 15:55 UTC, IegorSoboliev commented on business_register/pep_scoring/rules.py
>              acquisition_date__year__gte=2015,
Please, take into consideration here and in other rules that property can be rented. It is described in the right`s type:
```
        (OWNERSHIP, 'Ownership'),
        (BENEFICIAL_OWNERSHIP, 'Beneficial ownership'),
        (JOINT_OWNERSHIP, 'Joint ownership'),
        (COMMON_PROPERTY, 'Common property'),
        (RENT, 'Rent'),
        (USAGE, 'Usage'),
        (OTHER_USAGE_RIGHT, 'Other right of usage'),
        (OWNER_IS_ANOTHER_PERSON, 'Owner is another person'),
        (NO_INFO_FROM_FAMILY_MEMBER, 'Family member did not provide the information'),

```

2021-07-06 06:03 UTC, IegorSoboliev approved these changes

2021-07-06 06:39 UTC, IegorSoboliev requested changes

2021-07-06 06:39 UTC, IegorSoboliev commented on business_register/pep_scoring/rules.py
> +                       PropertyRight.COMMON_PROPERTY, PropertyRight.USAGE, PropertyRight.OTHER_USAGE_RIGHT]
definitely here shouldn`t be PropertyRight.USAGE, PropertyRight.OTHER_USAGE_RIGHT. Also, check, please COMMON_PROPERTY

2021-07-06 06:39 UTC, IegorSoboliev commented on business_register/pep_scoring/rules.py
> +                       PropertyRight.COMMON_PROPERTY, PropertyRight.USAGE, PropertyRight.OTHER_USAGE_RIGHT]
Discuss this Nastya, please

2021-07-06 06:39 UTC, IegorSoboliev commented on business_register/pep_scoring/rules.py
> +                       PropertyRight.COMMON_PROPERTY, PropertyRight.USAGE, PropertyRight.OTHER_USAGE_RIGHT]
And also take into consideration that any object can be owned by another person

2021-07-09 18:56 UTC, closed without merging