[DO-1770] Create PEP27 scoring rule
3v-workspace/Data_converter pull request #978
Opened 2021-07-06 08:31 UTC by Andrii17s

2021-07-06 09:48 UTC, IegorSoboliev commented on business_register/pep_scoring/rules.py
> +                          Property.GARAGE, Property.UNFINISHED_CONSTRUCTION, Property.OTHER, Property.OFFICE]
I think we should discuss with ANTAC do we need OTHER and OFFICE types here

2021-07-06 09:48 UTC, IegorSoboliev commented on business_register/pep_scoring/rules.py
> +            square_meters += property
I am not sure we can sum here

2021-07-06 09:48 UTC, IegorSoboliev commented on business_register/pep_scoring/rules.py
> +        for property in PropertyRight.objects.filter(
for `property_area` would be more clear, I guess

2021-07-06 17:05 UTC, IegorSoboliev approved these changes

2021-07-07 09:48 UTC, roman-tiukh requested changes

2021-07-07 09:48 UTC, roman-tiukh commented on business_register/pep_scoring/rules.py
> +            except:
except all errors its bad practice

2021-07-07 11:01 UTC, roman-tiukh requested changes

2021-07-07 11:01 UTC, roman-tiukh commented on business_register/pep_scoring/rules.py
> +        square_meters = serializers.IntegerField(min_value=0, required=True)
```suggestion
        square_meters = serializers.FloatField(min_value=0, required=True)
```

2021-07-07 12:25 UTC, roman-tiukh requested changes

2021-07-07 12:25 UTC, roman-tiukh commented on business_register/pep_scoring/rules.py
> +    message_en = 'amount of rented real estate exceeding 300 sq.m. {bigger_area_counter}',
```suggestion
    message_en = 'amount of rented real estate exceeding 300 sq.m. {bigger_area_counter}'
```

2021-07-07 12:36 UTC, roman-tiukh approved these changes

2021-07-07 12:36 UTC, merged